/**
 * Turns src/data/temp-listings.ts into SQL that loads the partner-app
 * listings into public.jobs for the Temp & hourly feed:
 *
 *   - upserts every listing (source = bluecrew | workwhile | instawork),
 *   - closes partner listings that are no longer in the file,
 *   - applies the equity filter: a listing whose employer misses its JUST
 *     Capital / As You Sow cutoff (per scout_settings) is closed, the same
 *     rule the Job Scout applies to scanned companies.
 *
 *   node scripts/temp-listings-sql.ts > supabase/migrations/<timestamp>_temp_listings.sql
 *
 * Then apply that migration (Supabase SQL editor, `supabase db push`, or Lovable).
 */
import {
  LISTINGS,
  LISTINGS_AS_OF,
  LISTINGS_VALID_DAYS,
  PARTNER_IDS,
  PARTNER_NAMES,
  PARTNER_SIGNUP_URLS,
  type TempListing,
} from "../src/data/temp-listings.ts";
import { normalizeCompanyName } from "../src/lib/scout/ratings.ts";
import { fingerprint, NAICS_SECTOR_OPTIONS } from "../src/lib/scout/refine.ts";

const q = (v: string | null) => (v === null ? "NULL" : `'${v.replace(/'/g, "''")}'`);
const arr = (xs: string[]) => `ARRAY[${xs.map(q).join(", ")}]::text[]`;
const slug = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const money = (n: number) => `$${Number.isInteger(n) ? n : n.toFixed(2)}`;

function payText(l: TempListing): string {
  if (l.pay.note) return l.pay.note;
  const r = l.pay.min === l.pay.max ? money(l.pay.min) : `${money(l.pay.min)}–${money(l.pay.max)}`;
  return l.pay.unit === "hour" ? `${r}/hr` : `${r} flat per shift`;
}

function description(l: TempListing): string {
  const app = PARTNER_NAMES[l.partner];
  const lines = [
    `${l.position} with ${l.company}, booked through ${app}.`,
    "",
    `Shifts (as listed on ${LISTINGS_AS_OF}):`,
    ...l.shifts.map((s) => `• ${s}`),
    "",
    `Pay: ${payText(l)}`,
    `Requirements: ${l.requirements.length ? l.requirements.join(", ") : "None listed"}`,
  ];
  if (l.interview !== undefined)
    lines.push(`Interview: ${l.interview ? "Required" : "Not required"}`);
  if (l.tags.length) lines.push(`${app} labels: ${l.tags.join(", ")}`);
  lines.push(
    "",
    `Sign up with ${app} and book this shift in their app. Shift times change daily, so check the app for what's open now.`,
  );
  return lines.join("\n");
}

const sector = (code: string) => NAICS_SECTOR_OPTIONS.find((o) => o.code === code)?.label ?? null;
const validThrough = new Date(
  Date.parse(`${LISTINGS_AS_OF}T23:59:59-07:00`) + LISTINGS_VALID_DAYS * 86_400_000,
).toISOString();

const rows = LISTINGS.map((l) => {
  const externalId = slug(`${l.company} ${l.position} ${l.location}`);
  return {
    externalId,
    normalized: normalizeCompanyName(l.company),
    values: [
      q(l.partner),
      q(externalId),
      q(l.position),
      q(l.company),
      q(l.location),
      q(description(l)),
      q(PARTNER_SIGNUP_URLS[l.partner]),
      q(sector(l.naics)),
      q(l.naics),
      q("temporary"),
      q("Temporary"),
      q("entry"),
      "false",
      q(`${LISTINGS_AS_OF}T12:00:00Z`),
      q(validThrough),
      q("hourly"),
      arr([`Shift work on ${PARTNER_NAMES[l.partner]}`]),
      String(l.pay.min),
      String(l.pay.max),
      q(l.pay.unit),
      q(fingerprint(l.company, l.position, l.location)),
    ].join(", "),
  };
});

const dupes = rows.filter((r, i) => rows.findIndex((x) => x.externalId === r.externalId) !== i);
if (dupes.length)
  throw new Error(`Duplicate listings: ${dupes.map((d) => d.externalId).join(", ")}`);

const partners = PARTNER_IDS.map(q).join(", ");
console.log(`-- Temp partner listings (${LISTINGS.length}) from src/data/temp-listings.ts, as of ${LISTINGS_AS_OF}.
-- Generated by scripts/temp-listings-sql.ts. Do not edit by hand.

INSERT INTO public.jobs (
  source, external_id, title, company_name, location, description, apply_url,
  industry, naics_code, employment_type, type, seniority, remote, posted_at,
  valid_through, track, track_reasons, pay_min, pay_max, pay_unit, fingerprint
) VALUES
${rows.map((r) => `  (${r.values})`).join(",\n")}
ON CONFLICT (source, external_id) DO UPDATE SET
  title = EXCLUDED.title,
  company_name = EXCLUDED.company_name,
  location = EXCLUDED.location,
  description = EXCLUDED.description,
  apply_url = EXCLUDED.apply_url,
  industry = EXCLUDED.industry,
  naics_code = EXCLUDED.naics_code,
  employment_type = EXCLUDED.employment_type,
  type = EXCLUDED.type,
  seniority = EXCLUDED.seniority,
  remote = EXCLUDED.remote,
  posted_at = EXCLUDED.posted_at,
  valid_through = EXCLUDED.valid_through,
  track = EXCLUDED.track,
  track_reasons = EXCLUDED.track_reasons,
  pay_min = EXCLUDED.pay_min,
  pay_max = EXCLUDED.pay_max,
  pay_unit = EXCLUDED.pay_unit,
  fingerprint = EXCLUDED.fingerprint,
  last_seen_at = now(),
  status = 'active';

-- Listings that dropped off the sheet come down.
UPDATE public.jobs
SET status = 'closed'
WHERE source IN (${partners})
  AND status <> 'closed'
  AND external_id NOT IN (${rows.map((r) => q(r.externalId)).join(", ")});

-- Equity filter: close listings whose employer is on a ratings list and misses
-- its cutoff ("all" mode: must pass every list it's on; "any": at least one).
WITH listing(external_id, normalized_name) AS (
  VALUES
${rows.map((r) => `    (${q(r.externalId)}, ${q(r.normalized)})`).join(",\n")}
), verdicts AS (
  SELECT l.external_id,
         -- As You Sow only applies from as_you_sow_min_employees employees up.
         bool_and(CASE WHEN r.source = 'just_capital' THEN r.rank <= s.just_capital_max_rank
                       WHEN r.employees < s.as_you_sow_min_employees THEN true
                       ELSE r.score >= s.as_you_sow_min_score END) AS passes_all,
         bool_or(CASE WHEN r.source = 'just_capital' THEN r.rank <= s.just_capital_max_rank
                      WHEN r.employees < s.as_you_sow_min_employees THEN true
                      ELSE r.score >= s.as_you_sow_min_score END) AS passes_any,
         s.ratings_mode
  FROM listing l
  JOIN public.company_ratings r ON r.normalized_name = l.normalized_name
  JOIN public.scout_settings s ON s.id = 1 AND s.ratings_enabled
  GROUP BY l.external_id, s.ratings_mode
)
UPDATE public.jobs j
SET status = 'closed',
    track_reasons = ARRAY['Employer below the equity filter cutoff']
FROM verdicts v
WHERE j.source IN (${partners})
  AND j.external_id = v.external_id
  AND NOT (CASE WHEN v.ratings_mode = 'any' THEN v.passes_any ELSE v.passes_all END);`);
