/**
 * Is a posting in the United States? The Job Scout only ingests U.S. jobs.
 *
 * Sources write locations every which way — "US, CA, Santa Clara",
 * "Boise, ID - Main Site", "Seattle-WA-2nd Ave", "Remote-USA",
 * "Fort Collins, Colorado, United States of America", "Pune, India",
 * "Israel, Yokneam", "Mexico City". The checks run strongest first:
 *
 *   1. an explicit U.S. country marker          → "us"
 *   2. a foreign country or a foreign-only city → "foreign"
 *   3. a U.S. state (name or code) or major city → "us"
 *   4. nothing to go on ("Remote", blank)       → "unknown"
 *
 * Step 2 runs before step 3 so "Toronto, ON, CA" and "Baja California, Mexico"
 * aren't mistaken for California, while "Ontario, CA" (a California city)
 * still counts as U.S. Only "us" is ingested.
 */

export type LocationVerdict = "us" | "foreign" | "unknown";

const US_COUNTRY = /\b(united states( of america)?|usa)\b/i;
// Upper-case only, so the word "us" in prose doesn't count.
const US_TOKEN = /(^|[^A-Za-z])US([^A-Za-z]|$)/;

const STATES: Record<string, string> = {
  AL: "alabama",
  AK: "alaska",
  AZ: "arizona",
  AR: "arkansas",
  CA: "california",
  CO: "colorado",
  CT: "connecticut",
  DE: "delaware",
  FL: "florida",
  GA: "georgia",
  HI: "hawaii",
  ID: "idaho",
  IL: "illinois",
  IN: "indiana",
  IA: "iowa",
  KS: "kansas",
  KY: "kentucky",
  LA: "louisiana",
  ME: "maine",
  MD: "maryland",
  MA: "massachusetts",
  MI: "michigan",
  MN: "minnesota",
  MS: "mississippi",
  MO: "missouri",
  MT: "montana",
  NE: "nebraska",
  NV: "nevada",
  NH: "new hampshire",
  NJ: "new jersey",
  NM: "new mexico",
  NY: "new york",
  NC: "north carolina",
  ND: "north dakota",
  OH: "ohio",
  OK: "oklahoma",
  OR: "oregon",
  PA: "pennsylvania",
  RI: "rhode island",
  SC: "south carolina",
  SD: "south dakota",
  TN: "tennessee",
  TX: "texas",
  UT: "utah",
  VT: "vermont",
  VA: "virginia",
  WA: "washington",
  WV: "west virginia",
  WI: "wisconsin",
  WY: "wyoming",
  DC: "district of columbia",
  PR: "puerto rico",
};
const STATE_NAME = new RegExp(`\\b(${Object.values(STATES).join("|")})\\b`, "i");

const US_CITIES = [
  "san francisco",
  "south san francisco",
  "oakland",
  "berkeley",
  "san jose",
  "santa clara",
  "sunnyvale",
  "mountain view",
  "palo alto",
  "menlo park",
  "redwood city",
  "fremont",
  "hayward",
  "san mateo",
  "cupertino",
  "milpitas",
  "walnut creek",
  "los angeles",
  "san diego",
  "sacramento",
  "new york",
  "new york city",
  "brooklyn",
  "manhattan",
  "seattle",
  "bellevue",
  "chicago",
  "boston",
  "austin",
  "dallas",
  "houston",
  "san antonio",
  "denver",
  "boulder",
  "atlanta",
  "miami",
  "orlando",
  "tampa",
  "phoenix",
  "portland",
  "salt lake city",
  "las vegas",
  "minneapolis",
  "detroit",
  "nashville",
  "charlotte",
  "raleigh",
  "durham",
  "philadelphia",
  "pittsburgh",
  "baltimore",
  "washington dc",
  "st louis",
  "kansas city",
  "columbus",
  "indianapolis",
  "cincinnati",
  "cleveland",
  "milwaukee",
  "honolulu",
];
const US_CITY = new RegExp(`\\b(${US_CITIES.join("|")})\\b`, "i");

const FOREIGN_COUNTRIES = [
  "canada",
  "mexico",
  "brazil",
  "argentina",
  "chile",
  "colombia",
  "peru",
  "costa rica",
  "guatemala",
  "panama",
  "uruguay",
  "ecuador",
  "venezuela",
  "dominican republic",
  "united kingdom",
  "uk",
  "england",
  "scotland",
  "wales",
  "northern ireland",
  "ireland",
  "france",
  "germany",
  "spain",
  "portugal",
  "italy",
  "netherlands",
  "belgium",
  "switzerland",
  "austria",
  "sweden",
  "norway",
  "denmark",
  "finland",
  "poland",
  "czech republic",
  "czechia",
  "hungary",
  "romania",
  "bulgaria",
  "greece",
  "turkey",
  "türkiye",
  "ukraine",
  "serbia",
  "croatia",
  "slovakia",
  "slovenia",
  "lithuania",
  "latvia",
  "estonia",
  "luxembourg",
  "iceland",
  "israel",
  "egypt",
  "south africa",
  "nigeria",
  "kenya",
  "morocco",
  "ghana",
  "saudi arabia",
  "united arab emirates",
  "uae",
  "qatar",
  "kuwait",
  "bahrain",
  "oman",
  "jordan",
  "india",
  "pakistan",
  "bangladesh",
  "sri lanka",
  "nepal",
  "china",
  "prc",
  "hong kong",
  "taiwan",
  "japan",
  "south korea",
  "korea",
  "singapore",
  "malaysia",
  "indonesia",
  "thailand",
  "vietnam",
  "viet nam",
  "philippines",
  "australia",
  "new zealand",
];
const FOREIGN_CITIES = [
  "bengaluru",
  "bangalore",
  "pune",
  "hyderabad",
  "chennai",
  "mumbai",
  "navi mumbai",
  "gurgaon",
  "gurugram",
  "noida",
  "new delhi",
  "kolkata",
  "ahmedabad",
  "mexico city",
  "ciudad de mexico",
  "guadalajara",
  "monterrey",
  "tlaquepaque",
  "sao paulo",
  "rio de janeiro",
  "buenos aires",
  "bogota",
  "toronto",
  "montreal",
  "markham",
  "mississauga",
  "calgary",
  "ottawa",
  "tbilisi",
  "shanghai",
  "beijing",
  "shenzhen",
  "guangzhou",
  "tokyo",
  "osaka",
  "hiroshima",
  "seoul",
  "taipei",
  "hsinchu",
  "taichung",
  "tainan",
  "taoyuan",
  "tel aviv",
  "yokneam",
  "haifa",
  "herzliya",
  "raanana",
  "cairo",
  "dubai",
  "abu dhabi",
  "riyadh",
  "lisbon",
  "porto",
  "madrid",
  "barcelona",
  "munich",
  "frankfurt",
  "amsterdam",
  "warsaw",
  "krakow",
  "prague",
  "budapest",
  "bucharest",
  "kuala lumpur",
  "penang",
  "batu kawan",
  "hanoi",
  "ho chi minh",
  "jakarta",
  "manila",
  "bangkok",
  "sydney",
  "melbourne",
  "st leonards",
  "auckland",
];
const FOREIGN = new RegExp(`\\b(${[...FOREIGN_COUNTRIES, ...FOREIGN_CITIES].join("|")})\\b`, "i");

/** Accents and dots dropped ("São Paulo" → "Sao Paulo", "U.S." → "US"); case kept for US_TOKEN. */
const fold = (s: string) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/\./g, "");

/** A two-letter state code standing alone between separators: ", CA", "-WA-", "ID - Main Site", "CA 95054". */
function hasStateCode(s: string): boolean {
  const parts = s.split(/[,;|/()\-–—]+/).map((p) => p.trim().replace(/\s+\d{5}(-\d{4})?$/, ""));
  return parts.some((p) => p in STATES);
}

export function classifyLocation(location: string | null | undefined): LocationVerdict {
  const raw = (location ?? "").trim();
  if (!raw) return "unknown";
  const s = fold(raw);

  if (US_COUNTRY.test(s) || US_TOKEN.test(s)) return "us";
  // "New Mexico" is a state, not Mexico.
  if (FOREIGN.test(s.replace(/new mexico/gi, ""))) return "foreign";
  if (hasStateCode(s) || STATE_NAME.test(s) || US_CITY.test(s)) return "us";
  return "unknown";
}

export const isUnitedStates = (location: string | null | undefined) =>
  classifyLocation(location) === "us";

/** Bay Area cities and counties, for preferring local postings when capping. */
export const BAY_AREA =
  /\b(san francisco|south san francisco|oakland|berkeley|emeryville|alameda|richmond|san leandro|hayward|fremont|newark|union city|san jose|santa clara|sunnyvale|mountain view|palo alto|menlo park|redwood city|san mateo|burlingame|foster city|san carlos|belmont|brisbane|daly city|san bruno|milpitas|cupertino|campbell|los gatos|walnut creek|concord|pleasanton|livermore|dublin|san ramon|danville|pleasant hill|novato|san rafael|petaluma|santa rosa|napa|vallejo|benicia|gilroy|morgan hill|marin|contra costa|bay area)\b/i;
