/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AutofillRouteImport } from './routes/autofill'
import { Route as CoachRouteRouteImport } from './routes/coach/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EmployerRatingsRouteImport } from './routes/employer-ratings'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as PreparationRouteImport } from './routes/preparation'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as RecruiterRouteRouteImport } from './routes/recruiter/route'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TalentRouteRouteImport } from './routes/talent/route'
import { Route as TemporaryStaffingRouteImport } from './routes/temporary-staffing'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAssignmentsRouteImport } from './routes/admin/assignments'
import { Route as AdminCoachInvitesRouteImport } from './routes/admin/coach-invites'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin/diagnostics'
import { Route as AdminInboxRouteImport } from './routes/admin/inbox'
import { Route as AdminJobsRouteImport } from './routes/admin/jobs'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminOrganizationsRouteImport } from './routes/admin/organizations'
import { Route as AdminRatingsRouteImport } from './routes/admin/ratings'
import { Route as AdminRecruitersRouteImport } from './routes/admin/recruiters'
import { Route as AdminScannersRouteImport } from './routes/admin/scanners'
import { Route as AdminScheduleRouteImport } from './routes/admin/schedule'
import { Route as AdminScoutRouteImport } from './routes/admin/scout'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTalentRouteImport } from './routes/admin/talent'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AutofillPrivacyRouteImport } from './routes/autofill_.privacy'
import { Route as CoachIndexRouteImport } from './routes/coach/index'
import { Route as CoachInboxRouteImport } from './routes/coach/inbox'
import { Route as CoachRecruitersRouteImport } from './routes/coach/recruiters'
import { Route as CoachScheduleRouteImport } from './routes/coach/schedule'
import { Route as CoachSettingsRouteImport } from './routes/coach/settings'
import { Route as CoachTalentRouteImport } from './routes/coach/talent'
import { Route as JoinCoachRouteImport } from './routes/join.coach'
import { Route as RecruiterIndexRouteImport } from './routes/recruiter/index'
import { Route as RecruiterAccountRouteImport } from './routes/recruiter/account'
import { Route as RecruiterApplicationsRouteImport } from './routes/recruiter/applications'
import { Route as RecruiterAssignedRouteImport } from './routes/recruiter/assigned'
import { Route as RecruiterCandidatesRouteImport } from './routes/recruiter/candidates'
import { Route as RecruiterCompanyRouteImport } from './routes/recruiter/company'
import { Route as RecruiterInboxRouteImport } from './routes/recruiter/inbox'
import { Route as RecruiterJobsRouteImport } from './routes/recruiter/jobs'
import { Route as RecruiterSavedRouteImport } from './routes/recruiter/saved'
import { Route as RecruiterScheduleRouteImport } from './routes/recruiter/schedule'
import { Route as RecruiterTalentRouteImport } from './routes/recruiter/talent'
import { Route as TalentIndexRouteImport } from './routes/talent/index'
import { Route as TalentAnswersRouteImport } from './routes/talent/answers'
import { Route as TalentApplicationsRouteImport } from './routes/talent/applications'
import { Route as TalentInboxRouteImport } from './routes/talent/inbox'
import { Route as TalentJobsRouteImport } from './routes/talent/jobs'
import { Route as TalentPreferencesRouteImport } from './routes/talent/preferences'
import { Route as TalentProfileRouteImport } from './routes/talent/profile'
import { Route as TalentSettingsRouteImport } from './routes/talent/settings'
import { Route as TalentTemporaryWorkRouteImport } from './routes/talent/temporary-work'
import { Route as ApiAutofillAnswersRouteImport } from './routes/api.autofill.answers'
import { Route as ApiAutofillPlanRouteImport } from './routes/api.autofill.plan'
import { Route as ApiScoutRunRouteImport } from './routes/api.scout.run'
import { Route as PreparationCareerProgramsProgramRouteImport } from './routes/preparation_.career-programs.$program'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutofillRoute = AutofillRouteImport.update({
  id: '/autofill',
  path: '/autofill',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRouteRoute = CoachRouteRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRatingsRoute = EmployerRatingsRouteImport.update({
  id: '/employer-ratings',
  path: '/employer-ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparationRoute = PreparationRouteImport.update({
  id: '/preparation',
  path: '/preparation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterRouteRoute = RecruiterRouteRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRouteRoute = TalentRouteRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const TemporaryStaffingRoute = TemporaryStaffingRouteImport.update({
  id: '/temporary-staffing',
  path: '/temporary-staffing',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoachInvitesRoute = AdminCoachInvitesRouteImport.update({
  id: '/coach-invites',
  path: '/coach-invites',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRatingsRoute = AdminRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRecruitersRoute = AdminRecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScannersRoute = AdminScannersRouteImport.update({
  id: '/scanners',
  path: '/scanners',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScoutRoute = AdminScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTalentRoute = AdminTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AutofillPrivacyRoute = AutofillPrivacyRouteImport.update({
  id: '/autofill_/privacy',
  path: '/autofill/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachInboxRoute = CoachInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachRecruitersRoute = CoachRecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachScheduleRoute = CoachScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachSettingsRoute = CoachSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CoachRouteRoute,
} as any)
const CoachTalentRoute = CoachTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => CoachRouteRoute,
} as any)
const JoinCoachRoute = JoinCoachRouteImport.update({
  id: '/join/coach',
  path: '/join/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterIndexRoute = RecruiterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecruiterRouteRoute,
} as any)
const RecruiterAccountRoute = RecruiterAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => RecruiterRouteRoute,
} as any)
const RecruiterApplicationsRoute = RecruiterApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => RecruiterRouteRoute,
} as any)
const RecruiterAssignedRoute = RecruiterAssignedRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => RecruiterRouteRoute,
} as any)
const RecruiterCandidatesRoute = RecruiterCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => RecruiterRouteRoute,
} as any)
const RecruiterCompanyRoute = RecruiterCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => RecruiterRouteRoute,
} as any)
const RecruiterInboxRoute = RecruiterInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => RecruiterRouteRoute,
} as any)
const RecruiterJobsRoute = RecruiterJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => RecruiterRouteRoute,
} as any)
const RecruiterSavedRoute = RecruiterSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => RecruiterRouteRoute,
} as any)
const RecruiterScheduleRoute = RecruiterScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => RecruiterRouteRoute,
} as any)
const RecruiterTalentRoute = RecruiterTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => RecruiterRouteRoute,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TalentRouteRoute,
} as any)
const TalentAnswersRoute = TalentAnswersRouteImport.update({
  id: '/answers',
  path: '/answers',
  getParentRoute: () => TalentRouteRoute,
} as any)
const TalentApplicationsRoute = TalentApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => TalentRouteRoute,
} as any)
const TalentInboxRoute = TalentInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => TalentRouteRoute,
} as any)
const TalentJobsRoute = TalentJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => TalentRouteRoute,
} as any)
const TalentPreferencesRoute = TalentPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => TalentRouteRoute,
} as any)
const TalentProfileRoute = TalentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TalentRouteRoute,
} as any)
const TalentSettingsRoute = TalentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TalentRouteRoute,
} as any)
const TalentTemporaryWorkRoute = TalentTemporaryWorkRouteImport.update({
  id: '/temporary-work',
  path: '/temporary-work',
  getParentRoute: () => TalentRouteRoute,
} as any)
const ApiAutofillAnswersRoute = ApiAutofillAnswersRouteImport.update({
  id: '/api/autofill/answers',
  path: '/api/autofill/answers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutofillPlanRoute = ApiAutofillPlanRouteImport.update({
  id: '/api/autofill/plan',
  path: '/api/autofill/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScoutRunRoute = ApiScoutRunRouteImport.update({
  id: '/api/scout/run',
  path: '/api/scout/run',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparationCareerProgramsProgramRoute =
  PreparationCareerProgramsProgramRouteImport.update({
    id: '/preparation_/career-programs/$program',
    path: '/preparation/career-programs/$program',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/coach': typeof CoachRouteRouteWithChildren
  '/recruiter': typeof RecruiterRouteRouteWithChildren
  '/talent': typeof TalentRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/autofill': typeof AutofillRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/employer-ratings': typeof EmployerRatingsRoute
  '/forbidden': typeof ForbiddenRoute
  '/insights': typeof InsightsRoute
  '/jobs': typeof JobsRoute
  '/preparation': typeof PreparationRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/temporary-staffing': typeof TemporaryStaffingRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/coach-invites': typeof AdminCoachInvitesRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/ratings': typeof AdminRatingsRoute
  '/admin/recruiters': typeof AdminRecruitersRoute
  '/admin/scanners': typeof AdminScannersRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/scout': typeof AdminScoutRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/talent': typeof AdminTalentRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/autofill/privacy': typeof AutofillPrivacyRoute
  '/coach/inbox': typeof CoachInboxRoute
  '/coach/recruiters': typeof CoachRecruitersRoute
  '/coach/schedule': typeof CoachScheduleRoute
  '/coach/settings': typeof CoachSettingsRoute
  '/coach/talent': typeof CoachTalentRoute
  '/join/coach': typeof JoinCoachRoute
  '/recruiter/account': typeof RecruiterAccountRoute
  '/recruiter/applications': typeof RecruiterApplicationsRoute
  '/recruiter/assigned': typeof RecruiterAssignedRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/company': typeof RecruiterCompanyRoute
  '/recruiter/inbox': typeof RecruiterInboxRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/saved': typeof RecruiterSavedRoute
  '/recruiter/schedule': typeof RecruiterScheduleRoute
  '/recruiter/talent': typeof RecruiterTalentRoute
  '/talent/answers': typeof TalentAnswersRoute
  '/talent/applications': typeof TalentApplicationsRoute
  '/talent/inbox': typeof TalentInboxRoute
  '/talent/jobs': typeof TalentJobsRoute
  '/talent/preferences': typeof TalentPreferencesRoute
  '/talent/profile': typeof TalentProfileRoute
  '/talent/settings': typeof TalentSettingsRoute
  '/talent/temporary-work': typeof TalentTemporaryWorkRoute
  '/admin/': typeof AdminIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/api/autofill/answers': typeof ApiAutofillAnswersRoute
  '/api/autofill/plan': typeof ApiAutofillPlanRoute
  '/api/scout/run': typeof ApiScoutRunRoute
  '/preparation/career-programs/$program': typeof PreparationCareerProgramsProgramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/autofill': typeof AutofillRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/employer-ratings': typeof EmployerRatingsRoute
  '/forbidden': typeof ForbiddenRoute
  '/insights': typeof InsightsRoute
  '/jobs': typeof JobsRoute
  '/preparation': typeof PreparationRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/temporary-staffing': typeof TemporaryStaffingRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/coach-invites': typeof AdminCoachInvitesRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/ratings': typeof AdminRatingsRoute
  '/admin/recruiters': typeof AdminRecruitersRoute
  '/admin/scanners': typeof AdminScannersRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/scout': typeof AdminScoutRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/talent': typeof AdminTalentRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/autofill/privacy': typeof AutofillPrivacyRoute
  '/coach/inbox': typeof CoachInboxRoute
  '/coach/recruiters': typeof CoachRecruitersRoute
  '/coach/schedule': typeof CoachScheduleRoute
  '/coach/settings': typeof CoachSettingsRoute
  '/coach/talent': typeof CoachTalentRoute
  '/join/coach': typeof JoinCoachRoute
  '/recruiter/account': typeof RecruiterAccountRoute
  '/recruiter/applications': typeof RecruiterApplicationsRoute
  '/recruiter/assigned': typeof RecruiterAssignedRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/company': typeof RecruiterCompanyRoute
  '/recruiter/inbox': typeof RecruiterInboxRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/saved': typeof RecruiterSavedRoute
  '/recruiter/schedule': typeof RecruiterScheduleRoute
  '/recruiter/talent': typeof RecruiterTalentRoute
  '/talent/answers': typeof TalentAnswersRoute
  '/talent/applications': typeof TalentApplicationsRoute
  '/talent/inbox': typeof TalentInboxRoute
  '/talent/jobs': typeof TalentJobsRoute
  '/talent/preferences': typeof TalentPreferencesRoute
  '/talent/profile': typeof TalentProfileRoute
  '/talent/settings': typeof TalentSettingsRoute
  '/talent/temporary-work': typeof TalentTemporaryWorkRoute
  '/admin': typeof AdminIndexRoute
  '/coach': typeof CoachIndexRoute
  '/recruiter': typeof RecruiterIndexRoute
  '/talent': typeof TalentIndexRoute
  '/api/autofill/answers': typeof ApiAutofillAnswersRoute
  '/api/autofill/plan': typeof ApiAutofillPlanRoute
  '/api/scout/run': typeof ApiScoutRunRoute
  '/preparation/career-programs/$program': typeof PreparationCareerProgramsProgramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/coach': typeof CoachRouteRouteWithChildren
  '/recruiter': typeof RecruiterRouteRouteWithChildren
  '/talent': typeof TalentRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/autofill': typeof AutofillRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/employer-ratings': typeof EmployerRatingsRoute
  '/forbidden': typeof ForbiddenRoute
  '/insights': typeof InsightsRoute
  '/jobs': typeof JobsRoute
  '/preparation': typeof PreparationRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/temporary-staffing': typeof TemporaryStaffingRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/coach-invites': typeof AdminCoachInvitesRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/ratings': typeof AdminRatingsRoute
  '/admin/recruiters': typeof AdminRecruitersRoute
  '/admin/scanners': typeof AdminScannersRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/scout': typeof AdminScoutRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/talent': typeof AdminTalentRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/autofill_/privacy': typeof AutofillPrivacyRoute
  '/coach/inbox': typeof CoachInboxRoute
  '/coach/recruiters': typeof CoachRecruitersRoute
  '/coach/schedule': typeof CoachScheduleRoute
  '/coach/settings': typeof CoachSettingsRoute
  '/coach/talent': typeof CoachTalentRoute
  '/join/coach': typeof JoinCoachRoute
  '/recruiter/account': typeof RecruiterAccountRoute
  '/recruiter/applications': typeof RecruiterApplicationsRoute
  '/recruiter/assigned': typeof RecruiterAssignedRoute
  '/recruiter/candidates': typeof RecruiterCandidatesRoute
  '/recruiter/company': typeof RecruiterCompanyRoute
  '/recruiter/inbox': typeof RecruiterInboxRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/saved': typeof RecruiterSavedRoute
  '/recruiter/schedule': typeof RecruiterScheduleRoute
  '/recruiter/talent': typeof RecruiterTalentRoute
  '/talent/answers': typeof TalentAnswersRoute
  '/talent/applications': typeof TalentApplicationsRoute
  '/talent/inbox': typeof TalentInboxRoute
  '/talent/jobs': typeof TalentJobsRoute
  '/talent/preferences': typeof TalentPreferencesRoute
  '/talent/profile': typeof TalentProfileRoute
  '/talent/settings': typeof TalentSettingsRoute
  '/talent/temporary-work': typeof TalentTemporaryWorkRoute
  '/admin/': typeof AdminIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/api/autofill/answers': typeof ApiAutofillAnswersRoute
  '/api/autofill/plan': typeof ApiAutofillPlanRoute
  '/api/scout/run': typeof ApiScoutRunRoute
  '/preparation_/career-programs/$program': typeof PreparationCareerProgramsProgramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/coach'
    | '/recruiter'
    | '/talent'
    | '/about'
    | '/auth'
    | '/autofill'
    | '/contact'
    | '/dashboard'
    | '/employer-ratings'
    | '/forbidden'
    | '/insights'
    | '/jobs'
    | '/preparation'
    | '/privacy'
    | '/programs'
    | '/reset-password'
    | '/services'
    | '/temporary-staffing'
    | '/terms'
    | '/verify-email'
    | '/admin/assignments'
    | '/admin/coach-invites'
    | '/admin/diagnostics'
    | '/admin/inbox'
    | '/admin/jobs'
    | '/admin/messages'
    | '/admin/organizations'
    | '/admin/ratings'
    | '/admin/recruiters'
    | '/admin/scanners'
    | '/admin/schedule'
    | '/admin/scout'
    | '/admin/settings'
    | '/admin/talent'
    | '/admin/users'
    | '/auth/callback'
    | '/autofill/privacy'
    | '/coach/inbox'
    | '/coach/recruiters'
    | '/coach/schedule'
    | '/coach/settings'
    | '/coach/talent'
    | '/join/coach'
    | '/recruiter/account'
    | '/recruiter/applications'
    | '/recruiter/assigned'
    | '/recruiter/candidates'
    | '/recruiter/company'
    | '/recruiter/inbox'
    | '/recruiter/jobs'
    | '/recruiter/saved'
    | '/recruiter/schedule'
    | '/recruiter/talent'
    | '/talent/answers'
    | '/talent/applications'
    | '/talent/inbox'
    | '/talent/jobs'
    | '/talent/preferences'
    | '/talent/profile'
    | '/talent/settings'
    | '/talent/temporary-work'
    | '/admin/'
    | '/coach/'
    | '/recruiter/'
    | '/talent/'
    | '/api/autofill/answers'
    | '/api/autofill/plan'
    | '/api/scout/run'
    | '/preparation/career-programs/$program'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/autofill'
    | '/contact'
    | '/dashboard'
    | '/employer-ratings'
    | '/forbidden'
    | '/insights'
    | '/jobs'
    | '/preparation'
    | '/privacy'
    | '/programs'
    | '/reset-password'
    | '/services'
    | '/temporary-staffing'
    | '/terms'
    | '/verify-email'
    | '/admin/assignments'
    | '/admin/coach-invites'
    | '/admin/diagnostics'
    | '/admin/inbox'
    | '/admin/jobs'
    | '/admin/messages'
    | '/admin/organizations'
    | '/admin/ratings'
    | '/admin/recruiters'
    | '/admin/scanners'
    | '/admin/schedule'
    | '/admin/scout'
    | '/admin/settings'
    | '/admin/talent'
    | '/admin/users'
    | '/auth/callback'
    | '/autofill/privacy'
    | '/coach/inbox'
    | '/coach/recruiters'
    | '/coach/schedule'
    | '/coach/settings'
    | '/coach/talent'
    | '/join/coach'
    | '/recruiter/account'
    | '/recruiter/applications'
    | '/recruiter/assigned'
    | '/recruiter/candidates'
    | '/recruiter/company'
    | '/recruiter/inbox'
    | '/recruiter/jobs'
    | '/recruiter/saved'
    | '/recruiter/schedule'
    | '/recruiter/talent'
    | '/talent/answers'
    | '/talent/applications'
    | '/talent/inbox'
    | '/talent/jobs'
    | '/talent/preferences'
    | '/talent/profile'
    | '/talent/settings'
    | '/talent/temporary-work'
    | '/admin'
    | '/coach'
    | '/recruiter'
    | '/talent'
    | '/api/autofill/answers'
    | '/api/autofill/plan'
    | '/api/scout/run'
    | '/preparation/career-programs/$program'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/coach'
    | '/recruiter'
    | '/talent'
    | '/about'
    | '/auth'
    | '/autofill'
    | '/contact'
    | '/dashboard'
    | '/employer-ratings'
    | '/forbidden'
    | '/insights'
    | '/jobs'
    | '/preparation'
    | '/privacy'
    | '/programs'
    | '/reset-password'
    | '/services'
    | '/temporary-staffing'
    | '/terms'
    | '/verify-email'
    | '/admin/assignments'
    | '/admin/coach-invites'
    | '/admin/diagnostics'
    | '/admin/inbox'
    | '/admin/jobs'
    | '/admin/messages'
    | '/admin/organizations'
    | '/admin/ratings'
    | '/admin/recruiters'
    | '/admin/scanners'
    | '/admin/schedule'
    | '/admin/scout'
    | '/admin/settings'
    | '/admin/talent'
    | '/admin/users'
    | '/auth/callback'
    | '/autofill_/privacy'
    | '/coach/inbox'
    | '/coach/recruiters'
    | '/coach/schedule'
    | '/coach/settings'
    | '/coach/talent'
    | '/join/coach'
    | '/recruiter/account'
    | '/recruiter/applications'
    | '/recruiter/assigned'
    | '/recruiter/candidates'
    | '/recruiter/company'
    | '/recruiter/inbox'
    | '/recruiter/jobs'
    | '/recruiter/saved'
    | '/recruiter/schedule'
    | '/recruiter/talent'
    | '/talent/answers'
    | '/talent/applications'
    | '/talent/inbox'
    | '/talent/jobs'
    | '/talent/preferences'
    | '/talent/profile'
    | '/talent/settings'
    | '/talent/temporary-work'
    | '/admin/'
    | '/coach/'
    | '/recruiter/'
    | '/talent/'
    | '/api/autofill/answers'
    | '/api/autofill/plan'
    | '/api/scout/run'
    | '/preparation_/career-programs/$program'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CoachRouteRoute: typeof CoachRouteRouteWithChildren
  RecruiterRouteRoute: typeof RecruiterRouteRouteWithChildren
  TalentRouteRoute: typeof TalentRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  AutofillRoute: typeof AutofillRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EmployerRatingsRoute: typeof EmployerRatingsRoute
  ForbiddenRoute: typeof ForbiddenRoute
  InsightsRoute: typeof InsightsRoute
  JobsRoute: typeof JobsRoute
  PreparationRoute: typeof PreparationRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  TemporaryStaffingRoute: typeof TemporaryStaffingRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AutofillPrivacyRoute: typeof AutofillPrivacyRoute
  JoinCoachRoute: typeof JoinCoachRoute
  ApiAutofillAnswersRoute: typeof ApiAutofillAnswersRoute
  ApiAutofillPlanRoute: typeof ApiAutofillPlanRoute
  ApiScoutRunRoute: typeof ApiScoutRunRoute
  PreparationCareerProgramsProgramRoute: typeof PreparationCareerProgramsProgramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autofill': {
      id: '/autofill'
      path: '/autofill'
      fullPath: '/autofill'
      preLoaderRoute: typeof AutofillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-ratings': {
      id: '/employer-ratings'
      path: '/employer-ratings'
      fullPath: '/employer-ratings'
      preLoaderRoute: typeof EmployerRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation': {
      id: '/preparation'
      path: '/preparation'
      fullPath: '/preparation'
      preLoaderRoute: typeof PreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter': {
      id: '/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof RecruiterRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temporary-staffing': {
      id: '/temporary-staffing'
      path: '/temporary-staffing'
      fullPath: '/temporary-staffing'
      preLoaderRoute: typeof TemporaryStaffingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/coach-invites': {
      id: '/admin/coach-invites'
      path: '/coach-invites'
      fullPath: '/admin/coach-invites'
      preLoaderRoute: typeof AdminCoachInvitesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ratings': {
      id: '/admin/ratings'
      path: '/ratings'
      fullPath: '/admin/ratings'
      preLoaderRoute: typeof AdminRatingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/recruiters': {
      id: '/admin/recruiters'
      path: '/recruiters'
      fullPath: '/admin/recruiters'
      preLoaderRoute: typeof AdminRecruitersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/scanners': {
      id: '/admin/scanners'
      path: '/scanners'
      fullPath: '/admin/scanners'
      preLoaderRoute: typeof AdminScannersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/scout': {
      id: '/admin/scout'
      path: '/scout'
      fullPath: '/admin/scout'
      preLoaderRoute: typeof AdminScoutRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/talent': {
      id: '/admin/talent'
      path: '/talent'
      fullPath: '/admin/talent'
      preLoaderRoute: typeof AdminTalentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/autofill_/privacy': {
      id: '/autofill_/privacy'
      path: '/autofill/privacy'
      fullPath: '/autofill/privacy'
      preLoaderRoute: typeof AutofillPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/inbox': {
      id: '/coach/inbox'
      path: '/inbox'
      fullPath: '/coach/inbox'
      preLoaderRoute: typeof CoachInboxRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/recruiters': {
      id: '/coach/recruiters'
      path: '/recruiters'
      fullPath: '/coach/recruiters'
      preLoaderRoute: typeof CoachRecruitersRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/schedule': {
      id: '/coach/schedule'
      path: '/schedule'
      fullPath: '/coach/schedule'
      preLoaderRoute: typeof CoachScheduleRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/settings': {
      id: '/coach/settings'
      path: '/settings'
      fullPath: '/coach/settings'
      preLoaderRoute: typeof CoachSettingsRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/coach/talent': {
      id: '/coach/talent'
      path: '/talent'
      fullPath: '/coach/talent'
      preLoaderRoute: typeof CoachTalentRouteImport
      parentRoute: typeof CoachRouteRoute
    }
    '/join/coach': {
      id: '/join/coach'
      path: '/join/coach'
      fullPath: '/join/coach'
      preLoaderRoute: typeof JoinCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/': {
      id: '/recruiter/'
      path: '/'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof RecruiterIndexRouteImport
      parentRoute: typeof RecruiterRouteRoute
    }
    '/recruiter/account': {
      id: '/recruiter/account'
      path: '/account'
      fullPath: '/recruiter/account'
      preLoaderRoute: typeof RecruiterAccountRouteImport
      parentRoute: typeof RecruiterRouteRoute
    }
    '/recruiter/applications': {
      id: '/recruiter/applications'
      path: '/applications'
      fullPath: '/recruiter/applications'
      preLoaderRoute: typeof RecruiterApplicationsRouteImport
      parentRoute: typeof RecruiterRouteRoute
    }
    '/recruiter/assigned': {
      id: '/recruiter/assigned'
      path: '/assigned'
      fullPath: '/recruiter/assigned'
      preLoaderRoute: typeof RecruiterAssignedRouteImport
      parentRoute: typeof RecruiterRouteRoute
    }
    '/recruiter/candidates': {
      id: '/recruiter/candidates'
      path: '/candidates'
      fullPath: '/recruiter/candidates'
      preLoaderRoute: typeof RecruiterCandidatesRouteImport
      parentRoute: typeof RecruiterRouteRoute
    }
    '/recruiter/company': {
      id: '/recruiter/company'
      path: '/company'
      fullPath: '/recruiter/company'
      preLoaderRoute: typeof RecruiterCompanyRouteImport
      parentRoute: typeof RecruiterRouteRoute
    }
    '/recruiter/inbox': {
      id: '/recruiter/inbox'
      path: '/inbox'
      fullPath: '/recruiter/inbox'
      preLoaderRoute: typeof RecruiterInboxRouteImport
      parentRoute: typeof RecruiterRouteRoute
    }
    '/recruiter/jobs': {
      id: '/recruiter/jobs'
      path: '/jobs'
      fullPath: '/recruiter/jobs'
      preLoaderRoute: typeof RecruiterJobsRouteImport
      parentRoute: typeof RecruiterRouteRoute
    }
    '/recruiter/saved': {
      id: '/recruiter/saved'
      path: '/saved'
      fullPath: '/recruiter/saved'
      preLoaderRoute: typeof RecruiterSavedRouteImport
      parentRoute: typeof RecruiterRouteRoute
    }
    '/recruiter/schedule': {
      id: '/recruiter/schedule'
      path: '/schedule'
      fullPath: '/recruiter/schedule'
      preLoaderRoute: typeof RecruiterScheduleRouteImport
      parentRoute: typeof RecruiterRouteRoute
    }
    '/recruiter/talent': {
      id: '/recruiter/talent'
      path: '/talent'
      fullPath: '/recruiter/talent'
      preLoaderRoute: typeof RecruiterTalentRouteImport
      parentRoute: typeof RecruiterRouteRoute
    }
    '/talent/': {
      id: '/talent/'
      path: '/'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof TalentRouteRoute
    }
    '/talent/answers': {
      id: '/talent/answers'
      path: '/answers'
      fullPath: '/talent/answers'
      preLoaderRoute: typeof TalentAnswersRouteImport
      parentRoute: typeof TalentRouteRoute
    }
    '/talent/applications': {
      id: '/talent/applications'
      path: '/applications'
      fullPath: '/talent/applications'
      preLoaderRoute: typeof TalentApplicationsRouteImport
      parentRoute: typeof TalentRouteRoute
    }
    '/talent/inbox': {
      id: '/talent/inbox'
      path: '/inbox'
      fullPath: '/talent/inbox'
      preLoaderRoute: typeof TalentInboxRouteImport
      parentRoute: typeof TalentRouteRoute
    }
    '/talent/jobs': {
      id: '/talent/jobs'
      path: '/jobs'
      fullPath: '/talent/jobs'
      preLoaderRoute: typeof TalentJobsRouteImport
      parentRoute: typeof TalentRouteRoute
    }
    '/talent/preferences': {
      id: '/talent/preferences'
      path: '/preferences'
      fullPath: '/talent/preferences'
      preLoaderRoute: typeof TalentPreferencesRouteImport
      parentRoute: typeof TalentRouteRoute
    }
    '/talent/profile': {
      id: '/talent/profile'
      path: '/profile'
      fullPath: '/talent/profile'
      preLoaderRoute: typeof TalentProfileRouteImport
      parentRoute: typeof TalentRouteRoute
    }
    '/talent/settings': {
      id: '/talent/settings'
      path: '/settings'
      fullPath: '/talent/settings'
      preLoaderRoute: typeof TalentSettingsRouteImport
      parentRoute: typeof TalentRouteRoute
    }
    '/talent/temporary-work': {
      id: '/talent/temporary-work'
      path: '/temporary-work'
      fullPath: '/talent/temporary-work'
      preLoaderRoute: typeof TalentTemporaryWorkRouteImport
      parentRoute: typeof TalentRouteRoute
    }
    '/api/autofill/answers': {
      id: '/api/autofill/answers'
      path: '/api/autofill/answers'
      fullPath: '/api/autofill/answers'
      preLoaderRoute: typeof ApiAutofillAnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autofill/plan': {
      id: '/api/autofill/plan'
      path: '/api/autofill/plan'
      fullPath: '/api/autofill/plan'
      preLoaderRoute: typeof ApiAutofillPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scout/run': {
      id: '/api/scout/run'
      path: '/api/scout/run'
      fullPath: '/api/scout/run'
      preLoaderRoute: typeof ApiScoutRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparation_/career-programs/$program': {
      id: '/preparation_/career-programs/$program'
      path: '/preparation/career-programs/$program'
      fullPath: '/preparation/career-programs/$program'
      preLoaderRoute: typeof PreparationCareerProgramsProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminCoachInvitesRoute: typeof AdminCoachInvitesRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminRatingsRoute: typeof AdminRatingsRoute
  AdminRecruitersRoute: typeof AdminRecruitersRoute
  AdminScannersRoute: typeof AdminScannersRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminScoutRoute: typeof AdminScoutRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTalentRoute: typeof AdminTalentRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminCoachInvitesRoute: AdminCoachInvitesRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminRatingsRoute: AdminRatingsRoute,
  AdminRecruitersRoute: AdminRecruitersRoute,
  AdminScannersRoute: AdminScannersRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminScoutRoute: AdminScoutRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTalentRoute: AdminTalentRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CoachRouteRouteChildren {
  CoachInboxRoute: typeof CoachInboxRoute
  CoachRecruitersRoute: typeof CoachRecruitersRoute
  CoachScheduleRoute: typeof CoachScheduleRoute
  CoachSettingsRoute: typeof CoachSettingsRoute
  CoachTalentRoute: typeof CoachTalentRoute
  CoachIndexRoute: typeof CoachIndexRoute
}

const CoachRouteRouteChildren: CoachRouteRouteChildren = {
  CoachInboxRoute: CoachInboxRoute,
  CoachRecruitersRoute: CoachRecruitersRoute,
  CoachScheduleRoute: CoachScheduleRoute,
  CoachSettingsRoute: CoachSettingsRoute,
  CoachTalentRoute: CoachTalentRoute,
  CoachIndexRoute: CoachIndexRoute,
}

const CoachRouteRouteWithChildren = CoachRouteRoute._addFileChildren(
  CoachRouteRouteChildren,
)

interface RecruiterRouteRouteChildren {
  RecruiterAccountRoute: typeof RecruiterAccountRoute
  RecruiterApplicationsRoute: typeof RecruiterApplicationsRoute
  RecruiterAssignedRoute: typeof RecruiterAssignedRoute
  RecruiterCandidatesRoute: typeof RecruiterCandidatesRoute
  RecruiterCompanyRoute: typeof RecruiterCompanyRoute
  RecruiterInboxRoute: typeof RecruiterInboxRoute
  RecruiterJobsRoute: typeof RecruiterJobsRoute
  RecruiterSavedRoute: typeof RecruiterSavedRoute
  RecruiterScheduleRoute: typeof RecruiterScheduleRoute
  RecruiterTalentRoute: typeof RecruiterTalentRoute
  RecruiterIndexRoute: typeof RecruiterIndexRoute
}

const RecruiterRouteRouteChildren: RecruiterRouteRouteChildren = {
  RecruiterAccountRoute: RecruiterAccountRoute,
  RecruiterApplicationsRoute: RecruiterApplicationsRoute,
  RecruiterAssignedRoute: RecruiterAssignedRoute,
  RecruiterCandidatesRoute: RecruiterCandidatesRoute,
  RecruiterCompanyRoute: RecruiterCompanyRoute,
  RecruiterInboxRoute: RecruiterInboxRoute,
  RecruiterJobsRoute: RecruiterJobsRoute,
  RecruiterSavedRoute: RecruiterSavedRoute,
  RecruiterScheduleRoute: RecruiterScheduleRoute,
  RecruiterTalentRoute: RecruiterTalentRoute,
  RecruiterIndexRoute: RecruiterIndexRoute,
}

const RecruiterRouteRouteWithChildren = RecruiterRouteRoute._addFileChildren(
  RecruiterRouteRouteChildren,
)

interface TalentRouteRouteChildren {
  TalentAnswersRoute: typeof TalentAnswersRoute
  TalentApplicationsRoute: typeof TalentApplicationsRoute
  TalentInboxRoute: typeof TalentInboxRoute
  TalentJobsRoute: typeof TalentJobsRoute
  TalentPreferencesRoute: typeof TalentPreferencesRoute
  TalentProfileRoute: typeof TalentProfileRoute
  TalentSettingsRoute: typeof TalentSettingsRoute
  TalentTemporaryWorkRoute: typeof TalentTemporaryWorkRoute
  TalentIndexRoute: typeof TalentIndexRoute
}

const TalentRouteRouteChildren: TalentRouteRouteChildren = {
  TalentAnswersRoute: TalentAnswersRoute,
  TalentApplicationsRoute: TalentApplicationsRoute,
  TalentInboxRoute: TalentInboxRoute,
  TalentJobsRoute: TalentJobsRoute,
  TalentPreferencesRoute: TalentPreferencesRoute,
  TalentProfileRoute: TalentProfileRoute,
  TalentSettingsRoute: TalentSettingsRoute,
  TalentTemporaryWorkRoute: TalentTemporaryWorkRoute,
  TalentIndexRoute: TalentIndexRoute,
}

const TalentRouteRouteWithChildren = TalentRouteRoute._addFileChildren(
  TalentRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CoachRouteRoute: CoachRouteRouteWithChildren,
  RecruiterRouteRoute: RecruiterRouteRouteWithChildren,
  TalentRouteRoute: TalentRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  AutofillRoute: AutofillRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EmployerRatingsRoute: EmployerRatingsRoute,
  ForbiddenRoute: ForbiddenRoute,
  InsightsRoute: InsightsRoute,
  JobsRoute: JobsRoute,
  PreparationRoute: PreparationRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  TemporaryStaffingRoute: TemporaryStaffingRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AutofillPrivacyRoute: AutofillPrivacyRoute,
  JoinCoachRoute: JoinCoachRoute,
  ApiAutofillAnswersRoute: ApiAutofillAnswersRoute,
  ApiAutofillPlanRoute: ApiAutofillPlanRoute,
  ApiScoutRunRoute: ApiScoutRunRoute,
  PreparationCareerProgramsProgramRoute: PreparationCareerProgramsProgramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
