-- =========================================================================
-- Employer-ethics gate for the Job Scout ("Passing Score from Auditor").
--
-- Before a company's postings are ingested, its name is checked against
--   JUST Capital rankings   — passes at rank <= just_capital_max_rank (50)
--   As You Sow DEI scores   — passes at score >= as_you_sow_min_score (40)
-- A company on a list that misses its cutoff is skipped and its live
-- postings are closed. A company on neither list goes through the normal
-- filters. Logic: src/lib/scout/ratings.ts. Source files: data/company-ratings/.
-- =========================================================================

CREATE TABLE public.company_ratings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source TEXT NOT NULL CHECK (source IN ('just_capital', 'as_you_sow')),
  company_name TEXT NOT NULL,
  normalized_name TEXT NOT NULL,
  rank INTEGER,                 -- JUST Capital overall rank
  score NUMERIC(5, 2),          -- As You Sow DEI score, 0–100
  year INTEGER,
  imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (source, normalized_name)
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.company_ratings TO authenticated;
GRANT ALL ON public.company_ratings TO service_role;
ALTER TABLE public.company_ratings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins manage company ratings" ON public.company_ratings
  FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE INDEX company_ratings_normalized_idx ON public.company_ratings (normalized_name);

ALTER TABLE public.scout_settings
  ADD COLUMN ratings_enabled BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN just_capital_max_rank INTEGER NOT NULL DEFAULT 50 CHECK (just_capital_max_rank > 0),
  ADD COLUMN as_you_sow_min_score NUMERIC(5, 2) NOT NULL DEFAULT 40 CHECK (as_you_sow_min_score BETWEEN 0 AND 100),
  ADD COLUMN ratings_mode TEXT NOT NULL DEFAULT 'all' CHECK (ratings_mode IN ('all', 'any'));

ALTER TABLE public.scout_companies
  ADD COLUMN rating_name TEXT,          -- name to look up when it differs from the display name
  ADD COLUMN rating_override TEXT CHECK (rating_override IN ('pass', 'fail')),
  ADD COLUMN last_rating TEXT;          -- human-readable verdict from the last scan

-- Shown to talent on each posting, e.g. {"JUST Capital #16","As You Sow DEI 44%"}.
ALTER TABLE public.jobs ADD COLUMN employer_badges TEXT[] NOT NULL DEFAULT '{}';

-- Seed: JUST Capital 2026 rankings (top 105, justcapital.com/rankings) and
-- As You Sow California DEI scores. Replace from Admin → Ratings when they update.
INSERT INTO public.company_ratings (source, company_name, normalized_name, rank, score, year) VALUES
  ('just_capital', 'HP Inc', 'hp', 1, NULL, 2026),
  ('just_capital', 'Union Pacific Corp', 'union pacific', 2, NULL, 2026),
  ('just_capital', 'Hewlett Packard Enterprise Company', 'hewlett packard enterprise', 3, NULL, 2026),
  ('just_capital', 'Dow Inc', 'dow', 4, NULL, 2026),
  ('just_capital', 'S&P Global Inc', 's and p global', 5, NULL, 2026),
  ('just_capital', 'Micron Technology Inc', 'micron technology', 6, NULL, 2026),
  ('just_capital', 'The Hartford Insurance Group', 'hartford insurance', 7, NULL, 2026),
  ('just_capital', 'M&T Bank Corp', 'm and t bank', 8, NULL, 2026),
  ('just_capital', 'Accenture plc', 'accenture', 9, NULL, 2026),
  ('just_capital', 'Zillow Group Inc', 'zillow', 10, NULL, 2026),
  ('just_capital', 'PayPal Holdings Inc', 'paypal', 11, NULL, 2026),
  ('just_capital', 'Salesforce.com Inc', 'salesforce', 12, NULL, 2026),
  ('just_capital', 'The Cigna Group', 'cigna', 13, NULL, 2026),
  ('just_capital', 'Ciena Corporation', 'ciena', 14, NULL, 2026),
  ('just_capital', 'ServiceNow Inc', 'servicenow', 15, NULL, 2026),
  ('just_capital', 'NVIDIA Corp', 'nvidia', 16, NULL, 2026),
  ('just_capital', 'Trane Technologies', 'trane technologies', 17, NULL, 2026),
  ('just_capital', 'Advanced Micro Devices Inc', 'advanced micro devices', 18, NULL, 2026),
  ('just_capital', 'Mastercard Inc', 'mastercard', 19, NULL, 2026),
  ('just_capital', 'Applied Materials Inc', 'applied materials', 20, NULL, 2026),
  ('just_capital', 'The Hershey Company', 'hershey', 21, NULL, 2026),
  ('just_capital', 'Verizon Communications Inc', 'verizon communications', 22, NULL, 2026),
  ('just_capital', 'The Allstate Corporation', 'allstate', 23, NULL, 2026),
  ('just_capital', 'Keysight Technologies Inc', 'keysight technologies', 24, NULL, 2026),
  ('just_capital', 'NetApp Inc', 'netapp', 25, NULL, 2026),
  ('just_capital', 'Lear Corporation', 'lear', 26, NULL, 2026),
  ('just_capital', 'Marathon Petroleum Corp', 'marathon petroleum', 27, NULL, 2026),
  ('just_capital', 'AbbVie Inc', 'abbvie', 28, NULL, 2026),
  ('just_capital', 'Qualcomm Inc', 'qualcomm', 29, NULL, 2026),
  ('just_capital', 'Equinix Inc', 'equinix', 30, NULL, 2026),
  ('just_capital', 'Digital Realty Trust Inc', 'digital realty trust', 31, NULL, 2026),
  ('just_capital', 'Intuit Inc', 'intuit', 32, NULL, 2026),
  ('just_capital', 'Prudential Financial Inc', 'prudential financial', 33, NULL, 2026),
  ('just_capital', 'Visa Inc', 'visa', 34, NULL, 2026),
  ('just_capital', 'Lam Research Corp', 'lam research', 35, NULL, 2026),
  ('just_capital', 'Workday Inc', 'workday', 36, NULL, 2026),
  ('just_capital', 'Eaton Corp plc', 'eaton', 37, NULL, 2026),
  ('just_capital', 'Jacobs Solutions Inc', 'jacobs solutions', 38, NULL, 2026),
  ('just_capital', 'Assurant Inc', 'assurant', 39, NULL, 2026),
  ('just_capital', 'Medtronic plc', 'medtronic', 40, NULL, 2026),
  ('just_capital', 'NIKE Inc', 'nike', 41, NULL, 2026),
  ('just_capital', 'Ball Corp', 'ball', 42, NULL, 2026),
  ('just_capital', 'Analog Devices Inc', 'analog devices', 43, NULL, 2026),
  ('just_capital', 'Becton, Dickinson and Company', 'becton dickinson', 44, NULL, 2026),
  ('just_capital', 'Harley-Davidson Inc', 'harley davidson', 45, NULL, 2026),
  ('just_capital', 'Ecolab Inc', 'ecolab', 46, NULL, 2026),
  ('just_capital', 'RTX Corp', 'rtx', 47, NULL, 2026),
  ('just_capital', 'Bank of New York - BNY', 'bank of new york bny', 48, NULL, 2026),
  ('just_capital', 'Merck & Co Inc', 'merck', 49, NULL, 2026),
  ('just_capital', 'Hasbro Inc', 'hasbro', 50, NULL, 2026),
  ('just_capital', 'Jones Lang LaSalle Inc', 'jones lang lasalle', 51, NULL, 2026),
  ('just_capital', 'BlackRock Inc', 'blackrock', 52, NULL, 2026),
  ('just_capital', 'Constellation Energy Corporation', 'constellation energy', 53, NULL, 2026),
  ('just_capital', 'Public Service Enterprise Group Inc', 'public service enterprise', 53, NULL, 2026),
  ('just_capital', 'LyondellBasell Industries N.V.', 'lyondellbasell industries n v', 55, NULL, 2026),
  ('just_capital', 'Texas Instruments Inc', 'texas instruments', 56, NULL, 2026),
  ('just_capital', 'Boston Scientific Corp', 'boston scientific', 57, NULL, 2026),
  ('just_capital', 'Devon Energy Corp', 'devon energy', 58, NULL, 2026),
  ('just_capital', 'Apple Inc', 'apple', 59, NULL, 2026),
  ('just_capital', 'PNC Financial Services Group Inc', 'pnc financial services', 60, NULL, 2026),
  ('just_capital', 'Huntington Bancshares Inc', 'huntington bancshares', 61, NULL, 2026),
  ('just_capital', 'Vertex Pharmaceuticals Inc', 'vertex pharmaceuticals', 62, NULL, 2026),
  ('just_capital', 'Marsh Insurance', 'marsh insurance', 63, NULL, 2026),
  ('just_capital', 'Graphic Packaging Holding Co', 'graphic packaging', 64, NULL, 2026),
  ('just_capital', 'Xylem Inc', 'xylem', 65, NULL, 2026),
  ('just_capital', 'Freeport-McMoRan Inc', 'freeport mcmoran', 66, NULL, 2026),
  ('just_capital', 'CBRE Group Inc', 'cbre', 67, NULL, 2026),
  ('just_capital', 'Autodesk Inc', 'autodesk', 68, NULL, 2026),
  ('just_capital', 'Johnson Controls International plc', 'johnson controls international', 69, NULL, 2026),
  ('just_capital', 'Cheniere Energy Inc', 'cheniere energy', 70, NULL, 2026),
  ('just_capital', 'Duke Energy Corporation', 'duke energy', 71, NULL, 2026),
  ('just_capital', 'Owens Corning', 'owens corning', 72, NULL, 2026),
  ('just_capital', 'Intel Corp', 'intel', 73, NULL, 2026),
  ('just_capital', 'Starbucks Corporation', 'starbucks', 74, NULL, 2026),
  ('just_capital', 'Humana Inc', 'humana', 75, NULL, 2026),
  ('just_capital', 'Nasdaq Inc', 'nasdaq', 76, NULL, 2026),
  ('just_capital', 'Fifth Third Bancorp', 'fifth third bancorp', 77, NULL, 2026),
  ('just_capital', 'Principal Financial Group Inc', 'principal financial', 78, NULL, 2026),
  ('just_capital', 'Bristol-Myers Squibb Co', 'bristol myers squibb', 79, NULL, 2026),
  ('just_capital', 'The Walt Disney Company', 'walt disney', 80, NULL, 2026),
  ('just_capital', 'Lowe''s Companies Inc', 'lowe s', 81, NULL, 2026),
  ('just_capital', 'Akamai Technologies Inc', 'akamai technologies', 82, NULL, 2026),
  ('just_capital', 'T-Mobile US Inc', 't mobile us', 83, NULL, 2026),
  ('just_capital', 'General Mills Inc', 'general mills', 84, NULL, 2026),
  ('just_capital', 'Oracle Corporation', 'oracle', 85, NULL, 2026),
  ('just_capital', 'Fiserv', 'fiserv', 86, NULL, 2026),
  ('just_capital', 'American Express Company', 'american express', 87, NULL, 2026),
  ('just_capital', 'Cummins Inc', 'cummins', 88, NULL, 2026),
  ('just_capital', 'Elevance Health', 'elevance health', 89, NULL, 2026),
  ('just_capital', 'Valero Energy Corp', 'valero energy', 90, NULL, 2026),
  ('just_capital', 'KLA Corp', 'kla', 91, NULL, 2026),
  ('just_capital', 'Illumina Inc', 'illumina', 92, NULL, 2026),
  ('just_capital', 'American Water Works Company Inc', 'american water works', 93, NULL, 2026),
  ('just_capital', 'PepsiCo Inc', 'pepsico', 94, NULL, 2026),
  ('just_capital', 'Organon & Co', 'organon', 95, NULL, 2026),
  ('just_capital', 'GE Vernova Inc', 'ge vernova', 96, NULL, 2026),
  ('just_capital', 'CVS Health Corporation', 'cvs health', 97, NULL, 2026),
  ('just_capital', 'Colgate-Palmolive Company', 'colgate palmolive', 98, NULL, 2026),
  ('just_capital', 'Synopsys Inc', 'synopsys', 99, NULL, 2026),
  ('just_capital', 'CoStar Group Inc', 'costar', 100, NULL, 2026),
  ('just_capital', 'Western Digital Corp', 'western digital', 101, NULL, 2026),
  ('just_capital', 'Abbott Laboratories', 'abbott laboratories', 102, NULL, 2026),
  ('just_capital', 'Cirrus Logic Inc', 'cirrus logic', 103, NULL, 2026),
  ('just_capital', 'Bath & Body Works Inc', 'bath and body works', 104, NULL, 2026),
  ('just_capital', 'Edison International', 'edison international', 105, NULL, 2026),
  ('as_you_sow', '10X GENOMICS, INC', '10x genomics', NULL, 0, NULL),
  ('as_you_sow', '4D MOLECULAR THERAPEUTICS, INC', '4d molecular therapeutics', NULL, 0, NULL),
  ('as_you_sow', '8X8', '8x8', NULL, 0, NULL),
  ('as_you_sow', 'A10 NETWORKS, INC', 'a10 networks', NULL, 0, NULL),
  ('as_you_sow', 'AARDVARK THERAPEUTICS, INC', 'aardvark therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'ACADIA PHARMACEUTICALS', 'acadia pharmaceuticals', NULL, 0, NULL),
  ('as_you_sow', 'ACM RESEARCH, INC', 'acm research', NULL, 0, NULL),
  ('as_you_sow', 'ADEIA INC', 'adeia', NULL, 3, NULL),
  ('as_you_sow', 'ADOBE INC', 'adobe', NULL, 41, NULL),
  ('as_you_sow', 'ADVANCED MICRO DEVICES', 'advanced micro devices', NULL, 41, NULL),
  ('as_you_sow', 'ADVANTAGE SOLUTIONS INC', 'advantage solutions', NULL, 3, NULL),
  ('as_you_sow', 'AEHR TEST SYSTEMS', 'aehr test systems', NULL, 0, NULL),
  ('as_you_sow', 'AELUMA, INC', 'aeluma', NULL, 0, NULL),
  ('as_you_sow', 'AEVA TECHNOLOGIES, INC', 'aeva technologies', NULL, 0, NULL),
  ('as_you_sow', 'AFFIRM HOLDINGS, INC', 'affirm', NULL, 7, NULL),
  ('as_you_sow', 'AGILENT TECHNOLOGIES, INC', 'agilent technologies', NULL, 3, NULL),
  ('as_you_sow', 'AIRBNB, INC', 'airbnb', NULL, 6, NULL),
  ('as_you_sow', 'ALECTOR, INC', 'alector', NULL, 2, NULL),
  ('as_you_sow', 'ALEXANDRIA REAL ESTATE EQUITIES, INC', 'alexandria real estate equities', NULL, 41, NULL),
  ('as_you_sow', 'ALIGNMENT HEALTHCARE, INC', 'alignment healthcare', NULL, 0, NULL),
  ('as_you_sow', 'ALLOGENE THERAPEUTICS, INC', 'allogene therapeutics', NULL, 7, NULL),
  ('as_you_sow', 'ALPHA AND OMEGA SEMICONDUCTOR', 'alpha and omega semiconductor', NULL, 39, NULL),
  ('as_you_sow', 'ALPHA TEKNOVA, INC', 'alpha teknova', NULL, 3, NULL),
  ('as_you_sow', 'ALPHABET INC', 'alphabet', NULL, 44, NULL),
  ('as_you_sow', 'ALPHATEC HOLDINGS, INC', 'alphatec', NULL, 0, NULL),
  ('as_you_sow', 'ALUMIS INC', 'alumis', NULL, 44, NULL),
  ('as_you_sow', 'AMBARELLA', 'ambarella', NULL, 2, NULL),
  ('as_you_sow', 'AMERICAN ASSETS TRUST, INC', 'american assets trust', NULL, 3, NULL),
  ('as_you_sow', 'AMERICAN HEALTHCARE REIT, INC', 'american healthcare reit', NULL, 0, NULL),
  ('as_you_sow', 'AMERICAN STATES WATER', 'american states water', NULL, 33, NULL),
  ('as_you_sow', 'AMERICAN VANGUARD', 'american vanguard', NULL, 37, NULL),
  ('as_you_sow', 'AMGEN', 'amgen', NULL, 11, NULL),
  ('as_you_sow', 'AMPHASTAR PHARMACEUTICALS, INC', 'amphastar pharmaceuticals', NULL, 0, NULL),
  ('as_you_sow', 'AMPLITUDE, INC', 'amplitude', NULL, 4, NULL),
  ('as_you_sow', 'ANAPTYSBIO', 'anaptysbio', NULL, 0, NULL),
  ('as_you_sow', 'ANNEXON, INC', 'annexon', NULL, 8, NULL),
  ('as_you_sow', 'APPFOLIO', 'appfolio', NULL, 9, NULL),
  ('as_you_sow', 'APPLE INC', 'apple', NULL, 26, NULL),
  ('as_you_sow', 'APPLIED MATERIALS', 'applied materials', NULL, 22, NULL),
  ('as_you_sow', 'APPLOVIN', 'applovin', NULL, 0, NULL),
  ('as_you_sow', 'ARCHER AVIATION INC', 'archer aviation', NULL, 0, NULL),
  ('as_you_sow', 'ARCTURUS THERAPEUTICS HOLDINGS INC', 'arcturus therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'ARCUS BIOSCIENCES, INC', 'arcus biosciences', NULL, 2, NULL),
  ('as_you_sow', 'ARCUTIS BIOTHERAPEUTICS, INC', 'arcutis biotherapeutics', NULL, 0, NULL),
  ('as_you_sow', 'ARDELYX, INC', 'ardelyx', NULL, 2, NULL),
  ('as_you_sow', 'ARES MANAGEMENT', 'ares management', NULL, 0, NULL),
  ('as_you_sow', 'ARISTA NETWORKS, INC', 'arista networks', NULL, 2, NULL),
  ('as_you_sow', 'ARLO TECHNOLOGIES, INC', 'arlo technologies', NULL, 2, NULL),
  ('as_you_sow', 'ARROWHEAD PHARMACEUTICALS, INC', 'arrowhead pharmaceuticals', NULL, 0, NULL),
  ('as_you_sow', 'ARS PHARMACEUTICALS, INC', 'ars pharmaceuticals', NULL, 0, NULL),
  ('as_you_sow', 'ARTERIS, INC', 'arteris', NULL, 0, NULL),
  ('as_you_sow', 'ASANA, INC', 'asana', NULL, 16, NULL),
  ('as_you_sow', 'ASTERA LABS, INC', 'astera labs', NULL, 13, NULL),
  ('as_you_sow', 'ASTRANA HEALTH, INC', 'astrana health', NULL, 0, NULL),
  ('as_you_sow', 'ATLASSIAN', 'atlassian', NULL, 22, NULL),
  ('as_you_sow', 'ATOMERA', 'atomera', NULL, 0, NULL),
  ('as_you_sow', 'Atrium Therapeutics, Inc', 'atrium therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'ATYR PHARMA', 'atyr pharma', NULL, 5, NULL),
  ('as_you_sow', 'AUTODESK, INC', 'autodesk', NULL, 43, NULL),
  ('as_you_sow', 'AVITA MEDICAL, INC', 'avita medical', NULL, 0, NULL),
  ('as_you_sow', 'BACKBLAZE, INC', 'backblaze', NULL, 0, NULL),
  ('as_you_sow', 'BANC OF CALIFORNIA, INC', 'banc of california', NULL, 10, NULL),
  ('as_you_sow', 'BANK OF MARIN BANCORP', 'bank of marin bancorp', NULL, 6, NULL),
  ('as_you_sow', 'BAYCOM', 'baycom', NULL, 0, NULL),
  ('as_you_sow', 'BEAUTY HEALTH', 'beauty health', NULL, 6, NULL),
  ('as_you_sow', 'BENITEC BIOPHARMA INC', 'benitec biopharma', NULL, 6, NULL),
  ('as_you_sow', 'BETA BIONICS, INC', 'beta bionics', NULL, 0, NULL),
  ('as_you_sow', 'BEYOND MEAT, INC', 'beyond meat', NULL, 24, NULL),
  ('as_you_sow', 'BIO RAD LABORATORIES, INC', 'bio rad laboratories', NULL, 2, NULL),
  ('as_you_sow', 'BIOAGE LABS, INC', 'bioage labs', NULL, 0, NULL),
  ('as_you_sow', 'BIOMARIN PHARMACEUTICAL', 'biomarin pharmaceutical', NULL, 9, NULL),
  ('as_you_sow', 'BITDEER TECHNOLOGIES GROUP', 'bitdeer technologies', NULL, 6, NULL),
  ('as_you_sow', 'BJS RESTAURANTS', 'bjs restaurants', NULL, 0, NULL),
  ('as_you_sow', 'BLACKLINE, INC', 'blackline', NULL, 8, NULL),
  ('as_you_sow', 'BLAIZE HOLDINGS, INC', 'blaize', NULL, 0, NULL),
  ('as_you_sow', 'BLEND LABS, INC', 'blend labs', NULL, 10, NULL),
  ('as_you_sow', 'BLOCK, INC', 'block', NULL, 27, NULL),
  ('as_you_sow', 'BLOOM ENERGY', 'bloom energy', NULL, 16, NULL),
  ('as_you_sow', 'BOOT BARN HOLDINGS, INC', 'boot barn', NULL, 0, NULL),
  ('as_you_sow', 'BOX', 'box', NULL, 6, NULL),
  ('as_you_sow', 'BRIDGEBIO PHARMA, INC', 'bridgebio pharma', NULL, 32, NULL),
  ('as_you_sow', 'BRIGHTSPIRE CAPITAL, INC', 'brightspire capital', NULL, 28, NULL),
  ('as_you_sow', 'BROADCOM INC', 'broadcom', NULL, 26, NULL),
  ('as_you_sow', 'C3.AI, INC', 'c3 ai', NULL, 0, NULL),
  ('as_you_sow', 'CADENCE DESIGN SYSTEMS', 'cadence design systems', NULL, 26, NULL),
  ('as_you_sow', 'CADIZ', 'cadiz', NULL, 0, NULL),
  ('as_you_sow', 'CALIFORNIA BANCORP \ CA', 'california bancorp', NULL, 4, NULL),
  ('as_you_sow', 'CALIFORNIA RESOURCES', 'california resources', NULL, 0, NULL),
  ('as_you_sow', 'CALIFORNIA WATER SERVICE GROUP', 'california water service', NULL, 29, NULL),
  ('as_you_sow', 'CALIX', 'calix', NULL, 4, NULL),
  ('as_you_sow', 'Callaway Golf', 'callaway golf', NULL, 0, NULL),
  ('as_you_sow', 'CAPRICOR THERAPEUTICS, INC', 'capricor therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'CARDIFF ONCOLOGY, INC', 'cardiff oncology', NULL, 0, NULL),
  ('as_you_sow', 'CAREDX, INC', 'caredx', NULL, 8, NULL),
  ('as_you_sow', 'CARETRUST REIT, INC', 'caretrust reit', NULL, 0, NULL),
  ('as_you_sow', 'CARLSMED, INC', 'carlsmed', NULL, 0, NULL),
  ('as_you_sow', 'CATHAY GENERAL BANCORP', 'cathay general bancorp', NULL, 8, NULL),
  ('as_you_sow', 'CENTRAL GARDEN AND PET', 'central garden and pet', NULL, 2, NULL),
  ('as_you_sow', 'CERIBELL, INC', 'ceribell', NULL, 0, NULL),
  ('as_you_sow', 'CERUS', 'cerus', NULL, 8, NULL),
  ('as_you_sow', 'CG ONCOLOGY, INC', 'cg oncology', NULL, 0, NULL),
  ('as_you_sow', 'CHEESECAKE FACTORY', 'cheesecake factory', NULL, 3, NULL),
  ('as_you_sow', 'CHEVRON', 'chevron', NULL, 28, NULL),
  ('as_you_sow', 'CHIPOTLE MEXICAN GRILL', 'chipotle mexican grill', NULL, 33, NULL),
  ('as_you_sow', 'CISCO SYSTEMS, INC', 'cisco systems', NULL, 26, NULL),
  ('as_you_sow', 'CLEAN ENERGY FUELS CORP', 'clean energy fuels', NULL, 4, NULL),
  ('as_you_sow', 'CLEARPOINT NEURO, INC', 'clearpoint neuro', NULL, 0, NULL),
  ('as_you_sow', 'CLOROX', 'clorox', NULL, 6, NULL),
  ('as_you_sow', 'CLOUDFLARE, INC', 'cloudflare', NULL, 8, NULL),
  ('as_you_sow', 'CODEXIS, INC', 'codexis', NULL, 0, NULL),
  ('as_you_sow', 'COHERUS ONCOLOGY, INC', 'coherus oncology', NULL, 0, NULL),
  ('as_you_sow', 'COHU', 'cohu', NULL, 29, NULL),
  ('as_you_sow', 'COMMUNITY WEST BANCSHARES', 'community west bancshares', NULL, 0, NULL),
  ('as_you_sow', 'COMPLETE SOLARIA, INC.', 'complete solaria', NULL, 0, NULL),
  ('as_you_sow', 'CONCENTRIX', 'concentrix', NULL, 0, NULL),
  ('as_you_sow', 'CONSENSUS CLOUD SOLUTIONS, INC', 'consensus cloud solutions', NULL, 6, NULL),
  ('as_you_sow', 'CONSUMER PORTFOLIO SERVICES, INC', 'consumer portfolio services', NULL, 0, NULL),
  ('as_you_sow', 'COOPER COMPANIES, INC', 'cooper', NULL, 38, NULL),
  ('as_you_sow', 'CORCEPT THERAPEUTICS', 'corcept therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'CORSAIR GAMING, INC', 'corsair gaming', NULL, 3, NULL),
  ('as_you_sow', 'CORVEL', 'corvel', NULL, 11, NULL),
  ('as_you_sow', 'CORVUS PHARMACEUTICALS, INC', 'corvus pharmaceuticals', NULL, 0, NULL),
  ('as_you_sow', 'COURSERA, INC', 'coursera', NULL, 6, NULL),
  ('as_you_sow', 'CREDO TECHNOLOGY GROUP HOLDING', 'credo technology', NULL, 6, NULL),
  ('as_you_sow', 'CRINETICS PHARMACEUTICALS, INC', 'crinetics pharmaceuticals', NULL, 0, NULL),
  ('as_you_sow', 'CVB FINANCIAL', 'cvb financial', NULL, 0, NULL),
  ('as_you_sow', 'CYTEK BIOSCIENCES, INC', 'cytek biosciences', NULL, 0, NULL),
  ('as_you_sow', 'CYTOKINETICS', 'cytokinetics', NULL, 0, NULL),
  ('as_you_sow', 'DAILY JOURNAL', 'daily journal', NULL, 0, NULL),
  ('as_you_sow', 'DAVE INC', 'dave', NULL, 0, NULL),
  ('as_you_sow', 'DECKERS OUTDOOR', 'deckers outdoor', NULL, 26, NULL),
  ('as_you_sow', 'DENALI THERAPEUTICS INC', 'denali therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'DESIGN THERAPEUTICS, INC', 'design therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'DEXCOM', 'dexcom', NULL, 36, NULL),
  ('as_you_sow', 'DINE BRANDS GLOBAL, INC', 'dine brands global', NULL, 13, NULL),
  ('as_you_sow', 'DOCUSIGN, INC', 'docusign', NULL, 26, NULL),
  ('as_you_sow', 'DOLBY LABORATORIES, INC', 'dolby laboratories', NULL, 14, NULL),
  ('as_you_sow', 'DOORDASH, INC', 'doordash', NULL, 23, NULL),
  ('as_you_sow', 'DOUGLAS EMMETT', 'douglas emmett', NULL, 0, NULL),
  ('as_you_sow', 'DOXIMITY, INC', 'doximity', NULL, 0, NULL),
  ('as_you_sow', 'DROPBOX, INC', 'dropbox', NULL, 6, NULL),
  ('as_you_sow', 'DUCOMMUN', 'ducommun', NULL, 2, NULL),
  ('as_you_sow', 'E.L.F. BEAUTY, INC', 'e l f beauty', NULL, 8, NULL),
  ('as_you_sow', 'EAST WEST BANCORP', 'east west bancorp', NULL, 10, NULL),
  ('as_you_sow', 'EBAY', 'ebay', NULL, 98, NULL),
  ('as_you_sow', 'EDISON INTERNATIONAL', 'edison international', NULL, 34, NULL),
  ('as_you_sow', 'EDWARDS LIFESCIENCES', 'edwards lifesciences', NULL, 43, NULL),
  ('as_you_sow', 'EGAIN', 'egain', NULL, 6, NULL),
  ('as_you_sow', 'EHEALTH, INC', 'ehealth', NULL, 6, NULL),
  ('as_you_sow', 'EL POLLO LOCO HOLDINGS, INC', 'el pollo loco', NULL, 6, NULL),
  ('as_you_sow', 'ELECTRONIC ARTS INC', 'electronic arts', NULL, 40, NULL),
  ('as_you_sow', 'ELEDON PHARMACEUTICALS, INC', 'eledon pharmaceuticals', NULL, 0, NULL),
  ('as_you_sow', 'EMERALD HOLDING, INC', 'emerald', NULL, 0, NULL),
  ('as_you_sow', 'ENCORE CAPITAL GROUP', 'encore capital', NULL, 0, NULL),
  ('as_you_sow', 'ENERGY RECOVERY, INC', 'energy recovery', NULL, 3, NULL),
  ('as_you_sow', 'ENOVIX', 'enovix', NULL, 36, NULL),
  ('as_you_sow', 'ENPHASE ENERGY, INC', 'enphase energy', NULL, 17, NULL),
  ('as_you_sow', 'ENSIGN GROUP', 'ensign', NULL, 9, NULL),
  ('as_you_sow', 'ENTRAVISION COMMUNICATIONS', 'entravision communications', NULL, 0, NULL),
  ('as_you_sow', 'ENVISTA HOLDINGS', 'envista', NULL, 10, NULL),
  ('as_you_sow', 'EQUINIX', 'equinix', NULL, 11, NULL),
  ('as_you_sow', 'ERASCA, INC', 'erasca', NULL, 0, NULL),
  ('as_you_sow', 'ESSEX PROPERTY TRUST, INC', 'essex property trust', NULL, 28, NULL),
  ('as_you_sow', 'Everpure Inc', 'everpure', NULL, 23, NULL),
  ('as_you_sow', 'EVGO INC', 'evgo', NULL, 11, NULL),
  ('as_you_sow', 'EVOLUS, INC', 'evolus', NULL, 0, NULL),
  ('as_you_sow', 'EVOMMUNE INC', 'evommune', NULL, 0, NULL),
  ('as_you_sow', 'EXELIXIS, INC', 'exelixis', NULL, 18, NULL),
  ('as_you_sow', 'EXPONENT', 'exponent', NULL, 0, NULL),
  ('as_you_sow', 'FARADAY FUTURE INTELLIGENT ELECTRIC INC', 'faraday future intelligent electric', NULL, 6, NULL),
  ('as_you_sow', 'FASTLY, INC', 'fastly', NULL, 3, NULL),
  ('as_you_sow', 'FATE THERAPEUTICS', 'fate therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'FIGS, INC', 'figs', NULL, 6, NULL),
  ('as_you_sow', 'FIRST AMERICAN FINANCIAL', 'first american financial', NULL, 3, NULL),
  ('as_you_sow', 'FIRST TRACKS BIOTHERAPEUTICS, INC', 'first tracks biotherapeutics', NULL, 0, NULL),
  ('as_you_sow', 'FIVE STAR BANCORP', 'five star bancorp', NULL, 0, NULL),
  ('as_you_sow', 'FIVE9, INC', 'five9', NULL, 4, NULL),
  ('as_you_sow', 'FORMFACTOR', 'formfactor', NULL, 0, NULL),
  ('as_you_sow', 'FORTINET, INC', 'fortinet', NULL, 40, NULL),
  ('as_you_sow', 'FOUR CORNERS PROPERTY TRUST, INC', 'four corners property trust', NULL, 0, NULL),
  ('as_you_sow', 'FRANKLIN RESOURCES', 'franklin resources', NULL, 8, NULL),
  ('as_you_sow', 'FRESHWORKS INC', 'freshworks', NULL, 0, NULL),
  ('as_you_sow', 'FULGENT GENETICS, INC', 'fulgent genetics', NULL, 0, NULL),
  ('as_you_sow', 'GAP', 'gap', NULL, 33, NULL),
  ('as_you_sow', 'GERON', 'geron', NULL, 0, NULL),
  ('as_you_sow', 'GIGACLOUD TECHNOLOGY', 'gigacloud technology', NULL, 0, NULL),
  ('as_you_sow', 'GILEAD SCIENCES, INC', 'gilead sciences', NULL, 46, NULL),
  ('as_you_sow', 'GITLAB INC', 'gitlab', NULL, 10, NULL),
  ('as_you_sow', 'GLAUKOS', 'glaukos', NULL, 30, NULL),
  ('as_you_sow', 'GOLD.COM, INC', 'gold', NULL, 0, NULL),
  ('as_you_sow', 'GOSSAMER BIO, INC', 'gossamer bio', NULL, 8, NULL),
  ('as_you_sow', 'GRAIL, INC', 'grail', NULL, 28, NULL),
  ('as_you_sow', 'GRANITE CONSTRUCTION', 'granite construction', NULL, 13, NULL),
  ('as_you_sow', 'GRID DYNAMICS HOLDINGS, INC', 'grid dynamics', NULL, 3, NULL),
  ('as_you_sow', 'GRINDR INC', 'grindr', NULL, 4, NULL),
  ('as_you_sow', 'GROCERY OUTLET HOLDING CORP', 'grocery outlet', NULL, 30, NULL),
  ('as_you_sow', 'GUARDANT HEALTH, INC', 'guardant health', NULL, 7, NULL),
  ('as_you_sow', 'GUIDEWIRE SOFTWARE, INC', 'guidewire software', NULL, 7, NULL),
  ('as_you_sow', 'GYRE THERAPEUTICS, INC', 'gyre therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'H2O AMERICA', 'h2o america', NULL, 0, NULL),
  ('as_you_sow', 'HALOZYME THERAPEUTICS, INC', 'halozyme therapeutics', NULL, 4, NULL),
  ('as_you_sow', 'HANMI FINANCIAL', 'hanmi financial', NULL, 0, NULL),
  ('as_you_sow', 'HARMONIC INC', 'harmonic', NULL, 26, NULL),
  ('as_you_sow', 'HERBALIFE LTD', 'herbalife', NULL, 6, NULL),
  ('as_you_sow', 'HERON THERAPEUTICS, INC', 'heron therapeutics', NULL, 8, NULL),
  ('as_you_sow', 'HIMS AND HERS HEALTH, INC', 'hims and hers health', NULL, 0, NULL),
  ('as_you_sow', 'HIPPO HOLDINGS INC', 'hippo', NULL, 0, NULL),
  ('as_you_sow', 'HONEST COMPANY, INC', 'honest', NULL, 6, NULL),
  ('as_you_sow', 'HOPE BANCORP', 'hope bancorp', NULL, 0, NULL),
  ('as_you_sow', 'HOULIHAN LOKEY, INC', 'houlihan lokey', NULL, 8, NULL),
  ('as_you_sow', 'HP', 'hp', NULL, 52, NULL),
  ('as_you_sow', 'HUDSON PACIFIC PROPERTIES, INC', 'hudson pacific properties', NULL, 26, NULL),
  ('as_you_sow', 'ICHOR HOLDINGS, LTD', 'ichor', NULL, 0, NULL),
  ('as_you_sow', 'ICU MEDICAL INC', 'icu medical', NULL, 9, NULL),
  ('as_you_sow', 'IDEAYA BIOSCIENCES, INC', 'ideaya biosciences', NULL, 10, NULL),
  ('as_you_sow', 'ILLUMINA, INC', 'illumina', NULL, 17, NULL),
  ('as_you_sow', 'IMMUNITYBIO, INC', 'immunitybio', NULL, 6, NULL),
  ('as_you_sow', 'INDIE SEMICONDUCTOR, INC', 'indie semiconductor', NULL, 6, NULL),
  ('as_you_sow', 'INGRAM MICRO HOLDING', 'ingram micro', NULL, 0, NULL),
  ('as_you_sow', 'INHIBRX BIOSCIENCES, INC', 'inhibrx biosciences', NULL, 0, NULL),
  ('as_you_sow', 'INNOVIVA, INC', 'innoviva', NULL, 2, NULL),
  ('as_you_sow', 'INOGEN', 'inogen', NULL, 0, NULL),
  ('as_you_sow', 'INSEEGO CORP', 'inseego', NULL, 2, NULL),
  ('as_you_sow', 'INTAPP, INC', 'intapp', NULL, 0, NULL),
  ('as_you_sow', 'INTEL', 'intel', NULL, 49, NULL),
  ('as_you_sow', 'INTUIT INC', 'intuit', NULL, 38, NULL),
  ('as_you_sow', 'INTUITIVE SURGICAL', 'intuitive surgical', NULL, 37, NULL),
  ('as_you_sow', 'IONIS PHARMACEUTICALS', 'ionis pharmaceuticals', NULL, 4, NULL),
  ('as_you_sow', 'IOVANCE BIOTHERAPEUTICS, INC', 'iovance biotherapeutics', NULL, 0, NULL),
  ('as_you_sow', 'IRHYTHM TECHNOLOGIES, INC', 'irhythm technologies', NULL, 9, NULL),
  ('as_you_sow', 'ISPIRE TECHNOLOGY INC', 'ispire technology', NULL, 55, NULL),
  ('as_you_sow', 'JACK IN THE BOX', 'jack in box', NULL, 4, NULL),
  ('as_you_sow', 'JAKKS PACIFIC', 'jakks pacific', NULL, 0, NULL),
  ('as_you_sow', 'JANUX THERAPEUTICS, INC', 'janux therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'JOBY AVIATION, INC', 'joby aviation', NULL, 2, NULL),
  ('as_you_sow', 'KAISER ALUMINUM', 'kaiser aluminum', NULL, 26, NULL),
  ('as_you_sow', 'KARAT PACKAGING INC', 'karat packaging', NULL, 0, NULL),
  ('as_you_sow', 'KARMAN HOLDINGS INC', 'karman', NULL, 0, NULL),
  ('as_you_sow', 'KB HOME', 'kb home', NULL, 2, NULL),
  ('as_you_sow', 'KENNEDY WILSON HOLDINGS, INC', 'kennedy wilson', NULL, 6, NULL),
  ('as_you_sow', 'KEYSIGHT TECHNOLOGIES, INC', 'keysight technologies', NULL, 15, NULL),
  ('as_you_sow', 'KILROY REALTY', 'kilroy realty', NULL, 8, NULL),
  ('as_you_sow', 'KLA', 'kla', NULL, 7, NULL),
  ('as_you_sow', 'KODIAK SCIENCES INC', 'kodiak sciences', NULL, 0, NULL),
  ('as_you_sow', 'KOLIBRI GLOBAL ENERGY INC', 'kolibri global energy', NULL, 0, NULL),
  ('as_you_sow', 'KORN FERRY', 'korn ferry', NULL, 6, NULL),
  ('as_you_sow', 'KRATOS DEFENSE AND SECURITY SOLUTIONS, INC', 'kratos defense and security solutions', NULL, 6, NULL),
  ('as_you_sow', 'KURA ONCOLOGY, INC', 'kura oncology', NULL, 0, NULL),
  ('as_you_sow', 'KURA SUSHI USA, INC', 'kura sushi usa', NULL, 0, NULL),
  ('as_you_sow', 'LAM RESEARCH', 'lam research', NULL, 36, NULL),
  ('as_you_sow', 'LEGALZOOM.COM, INC', 'legalzoom', NULL, 0, NULL),
  ('as_you_sow', 'LENDINGCLUB', 'lendingclub', NULL, 8, NULL),
  ('as_you_sow', 'LENZ THERAPEUTICS, INC', 'lenz therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'LIFE360, INC', 'life360', NULL, 6, NULL),
  ('as_you_sow', 'LIGAND PHARMACEUTICALS', 'ligand pharmaceuticals', NULL, 0, NULL),
  ('as_you_sow', 'LIMONEIRA', 'limoneira', NULL, 6, NULL),
  ('as_you_sow', 'LIONSGATE STUDIOS CORP', 'lionsgate studios', NULL, 6, NULL),
  ('as_you_sow', 'LIVE NATION ENTERTAINMENT, INC', 'live nation entertainment', NULL, 6, NULL),
  ('as_you_sow', 'LIVERAMP HOLDINGS, INC', 'liveramp', NULL, 0, NULL),
  ('as_you_sow', 'LOANDEPOT, INC', 'loandepot', NULL, 6, NULL),
  ('as_you_sow', 'LPL FINANCIAL HOLDINGS INC', 'lpl financial', NULL, 9, NULL),
  ('as_you_sow', 'LTC PROPERTIES', 'ltc properties', NULL, 6, NULL),
  ('as_you_sow', 'LUCID GROUP, INC', 'lucid', NULL, 7, NULL),
  ('as_you_sow', 'LUMENTUM HOLDINGS INC', 'lumentum', NULL, 27, NULL),
  ('as_you_sow', 'LYFT, INC', 'lyft', NULL, 16, NULL),
  ('as_you_sow', 'MACERICH', 'macerich', NULL, 65, NULL),
  ('as_you_sow', 'MAPLEBEAR INC', 'maplebear', NULL, 0, NULL),
  ('as_you_sow', 'MARAVAI LIFESCIENCES HOLDINGS, INC', 'maravai lifesciences', NULL, 6, NULL),
  ('as_you_sow', 'MARCUS AND MILLICHAP, INC', 'marcus and millichap', NULL, 0, NULL),
  ('as_you_sow', 'MARQETA, INC', 'marqeta', NULL, 10, NULL),
  ('as_you_sow', 'MASIMO', 'masimo', NULL, 6, NULL),
  ('as_you_sow', 'MATTEL', 'mattel', NULL, 35, NULL),
  ('as_you_sow', 'MAXLINEAR', 'maxlinear', NULL, 8, NULL),
  ('as_you_sow', 'MAZE THERAPEUTICS, INC', 'maze therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'MCGRATH RENTCORP', 'mcgrath rentcorp', NULL, 0, NULL),
  ('as_you_sow', 'MEDIAALPHA, INC', 'mediaalpha', NULL, 0, NULL),
  ('as_you_sow', 'MERCURY GENERAL', 'mercury general', NULL, 0, NULL),
  ('as_you_sow', 'META PLATFORMS, INC', 'meta platforms', NULL, 0, NULL),
  ('as_you_sow', 'MIRUM PHARMACEUTICALS, INC', 'mirum pharmaceuticals', NULL, 6, NULL),
  ('as_you_sow', 'MISSION PRODUCE, INC', 'mission produce', NULL, 0, NULL),
  ('as_you_sow', 'MITEK SYSTEMS', 'mitek systems', NULL, 6, NULL),
  ('as_you_sow', 'MOLINA HEALTHCARE, INC', 'molina healthcare', NULL, 0, NULL),
  ('as_you_sow', 'MONSTER BEVERAGE', 'monster beverage', NULL, 8, NULL),
  ('as_you_sow', 'MOTORCAR PARTS OF AMERICA', 'motorcar parts of america', NULL, 8, NULL),
  ('as_you_sow', 'NAVITAS SEMICONDUCTOR', 'navitas semiconductor', NULL, 0, NULL),
  ('as_you_sow', 'NERDWALLET, INC', 'nerdwallet', NULL, 10, NULL),
  ('as_you_sow', 'NETAPP, INC', 'netapp', NULL, 18, NULL),
  ('as_you_sow', 'NETFLIX', 'netflix', NULL, 65, NULL),
  ('as_you_sow', 'NETGEAR, INC', 'netgear', NULL, 31, NULL),
  ('as_you_sow', 'NEUROCRINE BIOSCIENCES', 'neurocrine biosciences', NULL, 13, NULL),
  ('as_you_sow', 'NEUROPACE', 'neuropace', NULL, 0, NULL),
  ('as_you_sow', 'NEXTDOOR HOLDINGS, INC', 'nextdoor', NULL, 0, NULL),
  ('as_you_sow', 'NEXTRACKER INC.', 'nextracker', NULL, 6, NULL),
  ('as_you_sow', 'NIAGEN BIOSCIENCE, INC', 'niagen bioscience', NULL, 0, NULL),
  ('as_you_sow', 'NKARTA, INC', 'nkarta', NULL, 0, NULL),
  ('as_you_sow', 'NMI HOLDINGS, INC', 'nmi', NULL, 6, NULL),
  ('as_you_sow', 'NURIX THERAPEUTICS, INC', 'nurix therapeutics', NULL, 22, NULL),
  ('as_you_sow', 'NUTANIX, INC', 'nutanix', NULL, 8, NULL),
  ('as_you_sow', 'NUVATION BIO INC', 'nuvation bio', NULL, 1, NULL),
  ('as_you_sow', 'NVIDIA', 'nvidia', NULL, 44, NULL),
  ('as_you_sow', 'OAK VALLEY BANCORP', 'oak valley bancorp', NULL, 0, NULL),
  ('as_you_sow', 'OKLO INC', 'oklo', NULL, 0, NULL),
  ('as_you_sow', 'OKTA, INC', 'okta', NULL, 38, NULL),
  ('as_you_sow', 'OLAPLEX HOLDINGS, INC', 'olaplex', NULL, 8, NULL),
  ('as_you_sow', 'OLEMA PHARMACEUTICALS, INC', 'olema pharmaceuticals', NULL, 8, NULL),
  ('as_you_sow', 'OMADA HEALTH, INC', 'omada health', NULL, 0, NULL),
  ('as_you_sow', 'OMNIAB, INC', 'omniab', NULL, 6, NULL),
  ('as_you_sow', 'ONCOLOGY INSTITUTE, INC', 'oncology institute', NULL, 0, NULL),
  ('as_you_sow', 'Onterris Inc', 'onterris', NULL, 6, NULL),
  ('as_you_sow', 'OOMA', 'ooma', NULL, 0, NULL),
  ('as_you_sow', 'OP BANCORP', 'op bancorp', NULL, 6, NULL),
  ('as_you_sow', 'OPORTUN FINANCIAL', 'oportun financial', NULL, 28, NULL),
  ('as_you_sow', 'ORIC PHARMACEUTICALS, INC', 'oric pharmaceuticals', NULL, 0, NULL),
  ('as_you_sow', 'ORUKA THERAPEUTICS, INC', 'oruka therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'OSI SYSTEMS', 'osi systems', NULL, 6, NULL),
  ('as_you_sow', 'OUSTER, INC', 'ouster', NULL, 0, NULL),
  ('as_you_sow', 'OUTSET MEDICAL, INC', 'outset medical', NULL, 19, NULL),
  ('as_you_sow', 'PACIFIC BIOSCIENCES OF CALIFORNIA, INC', 'pacific biosciences of california', NULL, 0, NULL),
  ('as_you_sow', 'PAGERDUTY, INC', 'pagerduty', NULL, 17, NULL),
  ('as_you_sow', 'PALO ALTO NETWORKS', 'palo alto networks', NULL, 26, NULL),
  ('as_you_sow', 'PALOMAR HOLDINGS, INC', 'palomar', NULL, 26, NULL),
  ('as_you_sow', 'PAYPAL HOLDINGS, INC', 'paypal', NULL, 8, NULL),
  ('as_you_sow', 'PCB BANCORP', 'pcb bancorp', NULL, 6, NULL),
  ('as_you_sow', 'PDF SOLUTIONS', 'pdf solutions', NULL, 6, NULL),
  ('as_you_sow', 'PENGUIN SOLUTIONS, INC', 'penguin solutions', NULL, 0, NULL),
  ('as_you_sow', 'PENNYMAC FINANCIAL SERVICES, INC', 'pennymac financial services', NULL, 37, NULL),
  ('as_you_sow', 'PENNYMAC MORTGAGE INVESTMENT TRUST', 'pennymac mortgage investment trust', NULL, 6, NULL),
  ('as_you_sow', 'PENUMBRA', 'penumbra', NULL, 26, NULL),
  ('as_you_sow', 'PERSONALIS, INC', 'personalis', NULL, 0, NULL),
  ('as_you_sow', 'PETCO HEALTH AND WELLNESS COMPANY, INC', 'petco health and wellness', NULL, 6, NULL),
  ('as_you_sow', 'PG AND E', 'pg and e', NULL, 75, NULL),
  ('as_you_sow', 'PINTEREST, INC', 'pinterest', NULL, 35, NULL),
  ('as_you_sow', 'PLANET LABS PBC', 'planet labs', NULL, 11, NULL),
  ('as_you_sow', 'POWER INTEGRATIONS', 'power integrations', NULL, 26, NULL),
  ('as_you_sow', 'PREFERRED BANK', 'preferred bank', NULL, 0, NULL),
  ('as_you_sow', 'PRICESMART', 'pricesmart', NULL, 6, NULL),
  ('as_you_sow', 'PRO DEX', 'pro dex', NULL, 1, NULL),
  ('as_you_sow', 'PROCEPT BIOROBOTICS', 'procept biorobotics', NULL, 6, NULL),
  ('as_you_sow', 'PROCORE TECHNOLOGIES, INC', 'procore technologies', NULL, 11, NULL),
  ('as_you_sow', 'PROLOGIS, INC', 'prologis', NULL, 11, NULL),
  ('as_you_sow', 'PROTAGONIST THERAPEUTICS', 'protagonist therapeutics', NULL, 8, NULL),
  ('as_you_sow', 'PUBLIC STORAGE', 'public storage', NULL, 29, NULL),
  ('as_you_sow', 'PUBMATIC, INC', 'pubmatic', NULL, 17, NULL),
  ('as_you_sow', 'PULMONX', 'pulmonx', NULL, 0, NULL),
  ('as_you_sow', 'PULSE BIOSCIENCES, INC', 'pulse biosciences', NULL, 0, NULL),
  ('as_you_sow', 'PUMA BIOTECHNOLOGY, INC', 'puma biotechnology', NULL, 6, NULL),
  ('as_you_sow', 'QUALCOMM INC', 'qualcomm', NULL, 26, NULL),
  ('as_you_sow', 'QUALYS, INC', 'qualys', NULL, 6, NULL),
  ('as_you_sow', 'QUANTUMSCAPE', 'quantumscape', NULL, 8, NULL),
  ('as_you_sow', 'QUIDELORTHO', 'quidelortho', NULL, 21, NULL),
  ('as_you_sow', 'QUINSTREET', 'quinstreet', NULL, 6, NULL),
  ('as_you_sow', 'RADNET, INC', 'radnet', NULL, 6, NULL),
  ('as_you_sow', 'RAMBUS', 'rambus', NULL, 6, NULL),
  ('as_you_sow', 'RBB BANCORP', 'rbb bancorp', NULL, 6, NULL),
  ('as_you_sow', 'REALTY INCOME', 'realty income', NULL, 26, NULL),
  ('as_you_sow', 'REDDIT, INC', 'reddit', NULL, 0, NULL),
  ('as_you_sow', 'REDWOOD TRUST', 'redwood trust', NULL, 18, NULL),
  ('as_you_sow', 'RESMED', 'resmed', NULL, 23, NULL),
  ('as_you_sow', 'RESOURCES CONNECTION, INC', 'resources connection', NULL, 6, NULL),
  ('as_you_sow', 'REVOLUTION MEDICINES, INC', 'revolution medicines', NULL, 8, NULL),
  ('as_you_sow', 'REVOLVE GROUP, INC', 'revolve', NULL, 0, NULL),
  ('as_you_sow', 'REXFORD INDUSTRIAL REALTY, INC', 'rexford industrial realty', NULL, 44, NULL),
  ('as_you_sow', 'REZOLUTE, INC', 'rezolute', NULL, 0, NULL),
  ('as_you_sow', 'RH', 'rh', NULL, 0, NULL),
  ('as_you_sow', 'RIGEL PHARMACEUTICALS', 'rigel pharmaceuticals', NULL, 6, NULL),
  ('as_you_sow', 'RIGETTI COMPUTING, INC', 'rigetti computing', NULL, 0, NULL),
  ('as_you_sow', 'RINGCENTRAL, INC', 'ringcentral', NULL, 10, NULL),
  ('as_you_sow', 'RIVIAN AUTOMOTIVE, INC. / DE', 'rivian automotive', NULL, 14, NULL),
  ('as_you_sow', 'ROBERT HALF INC', 'robert half', NULL, 26, NULL),
  ('as_you_sow', 'ROBINHOOD MARKETS, INC', 'robinhood markets', NULL, 0, NULL),
  ('as_you_sow', 'ROBLOX', 'roblox', NULL, 0, NULL),
  ('as_you_sow', 'ROCKET LAB', 'rocket lab', NULL, 0, NULL),
  ('as_you_sow', 'ROKU', 'roku', NULL, 1, NULL),
  ('as_you_sow', 'ROSS STORES, INC', 'ross stores', NULL, 43, NULL),
  ('as_you_sow', 'RUBRIK, INC', 'rubrik', NULL, 0, NULL),
  ('as_you_sow', 'RXSIGHT, INC', 'rxsight', NULL, 0, NULL),
  ('as_you_sow', 'SABRA HEALTH CARE REIT, INC', 'sabra health care reit', NULL, 9, NULL),
  ('as_you_sow', 'SALESFORCE, INC', 'salesforce', NULL, 31, NULL),
  ('as_you_sow', 'SAMSARA INC', 'samsara', NULL, 12, NULL),
  ('as_you_sow', 'SANDISK', 'sandisk', NULL, 0, NULL),
  ('as_you_sow', 'SANMINA', 'sanmina', NULL, 13, NULL),
  ('as_you_sow', 'SEMPRA', 'sempra', NULL, 92, NULL),
  ('as_you_sow', 'SEMTECH', 'semtech', NULL, 6, NULL),
  ('as_you_sow', 'SENTINELONE, INC', 'sentinelone', NULL, 0, NULL),
  ('as_you_sow', 'SEPTERNA, INC', 'septerna', NULL, 0, NULL),
  ('as_you_sow', 'SERVE ROBOTICS INC', 'serve robotics', NULL, 0, NULL),
  ('as_you_sow', 'SERVICENOW, INC', 'servicenow', NULL, 20, NULL),
  ('as_you_sow', 'SI BONE, INC', 'si bone', NULL, 6, NULL),
  ('as_you_sow', 'SIERRA BANCORP', 'sierra bancorp', NULL, 6, NULL),
  ('as_you_sow', 'SIGHT SCIENCES, INC', 'sight sciences', NULL, 0, NULL),
  ('as_you_sow', 'SILVACO GROUP, INC', 'silvaco', NULL, 0, NULL),
  ('as_you_sow', 'SIMPSON MANUFACTURING CO., INC', 'simpson manufacturing', NULL, 8, NULL),
  ('as_you_sow', 'SIMULATIONS PLUS, INC', 'simulations plus', NULL, 6, NULL),
  ('as_you_sow', 'SITIME', 'sitime', NULL, 30, NULL),
  ('as_you_sow', 'SKYWORKS SOLUTIONS, INC', 'skyworks solutions', NULL, 36, NULL),
  ('as_you_sow', 'SMARTSTOP SELF STORAGE REIT, INC', 'smartstop self storage reit', NULL, 0, NULL),
  ('as_you_sow', 'SOFI TECHNOLOGIES, INC', 'sofi technologies', NULL, 16, NULL),
  ('as_you_sow', 'SONOS', 'sonos', NULL, 10, NULL),
  ('as_you_sow', 'SOUNDHOUND AI, INC', 'soundhound ai', NULL, 7, NULL),
  ('as_you_sow', 'SOUNDTHINKING, INC', 'soundthinking', NULL, 10, NULL),
  ('as_you_sow', 'STAAR SURGICAL', 'staar surgical', NULL, 6, NULL),
  ('as_you_sow', 'STANDARD BIOTOOLS INC', 'standard biotools', NULL, 6, NULL),
  ('as_you_sow', 'STARZ ENTERTAINMENT', 'starz entertainment', NULL, 0, NULL),
  ('as_you_sow', 'STITCH FIX, INC', 'stitch fix', NULL, 11, NULL),
  ('as_you_sow', 'SUMMIT THERAPEUTICS INC', 'summit therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'SUNRUN INC', 'sunrun', NULL, 6, NULL),
  ('as_you_sow', 'SUNSTONE HOTEL INVESTORS, INC', 'sunstone hotel investors', NULL, 8, NULL),
  ('as_you_sow', 'SUPER MICRO COMPUTER, INC', 'super micro computer', NULL, 6, NULL),
  ('as_you_sow', 'SWEETGREEN, INC', 'sweetgreen', NULL, 6, NULL),
  ('as_you_sow', 'SYNAPTICS', 'synaptics', NULL, 6, NULL),
  ('as_you_sow', 'SYNOPSYS', 'synopsys', NULL, 14, NULL),
  ('as_you_sow', 'TANDEM DIABETES CARE', 'tandem diabetes care', NULL, 6, NULL),
  ('as_you_sow', 'TARSUS PHARMACEUTICALS, INC', 'tarsus pharmaceuticals', NULL, 6, NULL),
  ('as_you_sow', 'TD SYNNEX', 'td synnex', NULL, 12, NULL),
  ('as_you_sow', 'TEJON RANCH', 'tejon ranch', NULL, 6, NULL),
  ('as_you_sow', 'TELEDYNE TECHNOLOGIES', 'teledyne technologies', NULL, 9, NULL),
  ('as_you_sow', 'TERADATA', 'teradata', NULL, 6, NULL),
  ('as_you_sow', 'TERRENO REALTY', 'terreno realty', NULL, 6, NULL),
  ('as_you_sow', 'TETRA TECH', 'tetra tech', NULL, 6, NULL),
  ('as_you_sow', 'THEREALREAL, INC', 'therealreal', NULL, 10, NULL),
  ('as_you_sow', 'THIRD HARMONIC BIO', 'third harmonic bio', NULL, 0, NULL),
  ('as_you_sow', 'THREDUP INC', 'thredup', NULL, 0, NULL),
  ('as_you_sow', 'TORRID HOLDINGS INC', 'torrid', NULL, 9, NULL),
  ('as_you_sow', 'TPG RE FINANCE TRUST, INC', 'tpg re finance trust', NULL, 0, NULL),
  ('as_you_sow', 'TRADE DESK, INC', 'trade desk', NULL, 6, NULL),
  ('as_you_sow', 'TRAVERE THERAPEUTICS, INC', 'travere therapeutics', NULL, 6, NULL),
  ('as_you_sow', 'TRICO BANCSHARES', 'trico bancshares', NULL, 0, NULL),
  ('as_you_sow', 'TRINET GROUP, INC', 'trinet', NULL, 0, NULL),
  ('as_you_sow', 'TTM TECHNOLOGIES', 'ttm technologies', NULL, 6, NULL),
  ('as_you_sow', 'TUTOR PERINI', 'tutor perini', NULL, 8, NULL),
  ('as_you_sow', 'TWILIO', 'twilio', NULL, 6, NULL),
  ('as_you_sow', 'TWIST BIOSCIENCE', 'twist bioscience', NULL, 6, NULL),
  ('as_you_sow', 'TYRA BIOSCIENCES, INC', 'tyra biosciences', NULL, 0, NULL),
  ('as_you_sow', 'UBER TECHNOLOGIES', 'uber technologies', NULL, 26, NULL),
  ('as_you_sow', 'ULTRA CLEAN HOLDINGS, INC', 'ultra clean', NULL, 0, NULL),
  ('as_you_sow', 'ULTRAGENYX PHARMACEUTICAL INC', 'ultragenyx pharmaceutical', NULL, 6, NULL),
  ('as_you_sow', 'UNITY SOFTWARE INC', 'unity software', NULL, 2, NULL),
  ('as_you_sow', 'UPSTART HOLDINGS, INC', 'upstart', NULL, 0, NULL),
  ('as_you_sow', 'UPWORK', 'upwork', NULL, 26, NULL),
  ('as_you_sow', 'VAXCYTE, INC', 'vaxcyte', NULL, 0, NULL),
  ('as_you_sow', 'VEEVA SYSTEMS', 'veeva systems', NULL, 8, NULL),
  ('as_you_sow', 'VELOCITY FINANCIAL, INC', 'velocity financial', NULL, 6, NULL),
  ('as_you_sow', 'VERA THERAPEUTICS, INC', 'vera therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'VERACYTE, INC', 'veracyte', NULL, 8, NULL),
  ('as_you_sow', 'VIANT TECHNOLOGY INC', 'viant technology', NULL, 0, NULL),
  ('as_you_sow', 'VIASAT', 'viasat', NULL, 22, NULL),
  ('as_you_sow', 'VIKING THERAPEUTICS, INC', 'viking therapeutics', NULL, 0, NULL),
  ('as_you_sow', 'VIR BIOTECHNOLOGY, INC', 'vir biotechnology', NULL, 26, NULL),
  ('as_you_sow', 'VIRCO MFG', 'virco mfg', NULL, 0, NULL),
  ('as_you_sow', 'VISA INC', 'visa', NULL, 26, NULL),
  ('as_you_sow', 'WALT DISNEY', 'walt disney', NULL, 74, NULL),
  ('as_you_sow', 'WD 40', 'wd 40', NULL, 13, NULL),
  ('as_you_sow', 'WEALTHFRONT', 'wealthfront', NULL, 0, NULL),
  ('as_you_sow', 'WEBTOON ENTERTAINMENT INC', 'webtoon entertainment', NULL, 0, NULL),
  ('as_you_sow', 'WELLS FARGO AND COMPANY', 'wells fargo', NULL, 46, NULL),
  ('as_you_sow', 'WESTAMERICA BANCORPORATION', 'westamerica bancorporation', NULL, 0, NULL),
  ('as_you_sow', 'WESTERN DIGITAL', 'western digital', NULL, 42, NULL),
  ('as_you_sow', 'WILLDAN GROUP, INC', 'willdan', NULL, 0, NULL),
  ('as_you_sow', 'WILLIAMS SONOMA', 'williams sonoma', NULL, 2, NULL),
  ('as_you_sow', 'WORKDAY, INC', 'workday', NULL, 10, NULL),
  ('as_you_sow', 'XENCOR', 'xencor', NULL, 6, NULL),
  ('as_you_sow', 'XOMA ROYALTY', 'xoma royalty', NULL, 6, NULL),
  ('as_you_sow', 'XPERI INC', 'xperi', NULL, 8, NULL),
  ('as_you_sow', 'XPONENTIAL FITNESS, INC', 'xponential fitness', NULL, 6, NULL),
  ('as_you_sow', 'YELP', 'yelp', NULL, 17, NULL),
  ('as_you_sow', 'ZEVIA PBC', 'zevia', NULL, 5, NULL),
  ('as_you_sow', 'ZIPRECRUITER, INC', 'ziprecruiter', NULL, 0, NULL),
  ('as_you_sow', 'ZOOM COMMUNICATIONS, INC', 'zoom communications', NULL, 6, NULL),
  ('as_you_sow', 'ZSCALER, INC', 'zscaler', NULL, 6, NULL);
