-- Temp partner listings (27) from src/data/temp-listings.ts, as of 2026-09-27.
-- Generated by scripts/temp-listings-sql.ts. Do not edit by hand.

INSERT INTO public.jobs (
  source, external_id, title, company_name, location, description, apply_url,
  industry, naics_code, employment_type, type, seniority, remote, posted_at,
  valid_through, track, track_reasons, pay_min, pay_max, pay_unit, fingerprint
) VALUES
  ('bluecrew', 'collision-auto-parts-driver-hayward-ca', 'Driver', 'Collision Auto Parts', 'Hayward, CA', 'Driver with Collision Auto Parts, booked through Bluecrew.

Shifts (as listed on 2026-09-27):
• Flexible (as needed)

Pay: $21/hr
Requirements: Driver''s license
Interview: Required

Sign up with Bluecrew and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.bluecrewjobs.com/', 'Transportation and Warehousing', '48', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Bluecrew']::text[], 21, 21, 'hour', 'collision auto parts|driver|hayward ca'),
  ('bluecrew', 'jitsu-warehouse-associate-san-leandro-ca', 'Warehouse Associate', 'Jitsu', 'San Leandro, CA', 'Warehouse Associate with Jitsu, booked through Bluecrew.

Shifts (as listed on 2026-09-27):
• Saturday + Sunday, 5:30pm – 11:30pm

Pay: $18/hr
Requirements: Physical labor
Interview: Not required

Sign up with Bluecrew and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.bluecrewjobs.com/', 'Transportation and Warehousing', '48', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Bluecrew']::text[], 18, 18, 'hour', 'jitsu|warehouse associate|san leandro ca'),
  ('bluecrew', 'sharebite-server-san-francisco-ca', 'Server', 'Sharebite', 'San Francisco, CA', 'Server with Sharebite, booked through Bluecrew.

Shifts (as listed on 2026-09-27):
• Monday – Thursday, 11:00am – 3:00pm

Pay: $26/hr
Requirements: Food handler card
Interview: Required

Sign up with Bluecrew and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.bluecrewjobs.com/', 'Accommodation and Food Services', '72', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Bluecrew']::text[], 26, 26, 'hour', 'sharebite|server|san francisco ca'),
  ('workwhile', 'advantage-solutions-costco-sample-demonstrator-newark-ca', 'Costco Sample Demonstrator', 'Advantage Solutions', 'Newark, CA', 'Costco Sample Demonstrator with Advantage Solutions, booked through WorkWhile.

Shifts (as listed on 2026-09-27):
• Sun 9/27, 10:00am – 4:15pm

Pay: $20.37/hr
Requirements: Food handler card, Experience needed

Sign up with WorkWhile and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.workwhile.ai/for-workers', 'Retail Trade', '44', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on WorkWhile']::text[], 20.37, 20.37, 'hour', 'advantage solutions|costco sample demonstrator|newark ca'),
  ('workwhile', 'jitsu-delivery-driver-san-leandro-ca', 'Delivery Driver', 'Jitsu', 'San Leandro, CA', 'Delivery Driver with Jitsu, booked through WorkWhile.

Shifts (as listed on 2026-09-27):
• Sun 9/27, 11:00am – 3:00pm
• Sun 9/27, 1:00pm – 5:00pm
• Sun 9/27, 2:00pm – 6:00pm

Pay: $110 flat per shift
Requirements: Driver''s license, Insurance, Own vehicle, Heavy lifting
WorkWhile labels: Flat rate

Sign up with WorkWhile and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.workwhile.ai/for-workers', 'Transportation and Warehousing', '48', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on WorkWhile']::text[], 110, 110, 'shift', 'jitsu|delivery driver|san leandro ca'),
  ('workwhile', 'jitsu-delivery-driver-flat-rate-south-san-francisco-ca', 'Delivery Driver (flat rate)', 'Jitsu', 'South San Francisco, CA', 'Delivery Driver (flat rate) with Jitsu, booked through WorkWhile.

Shifts (as listed on 2026-09-27):
• Sun 9/27, 10:00am – 2:00pm
• Sun 9/27, 2:00pm – 6:00pm

Pay: $95 flat (10am shift); $109 + $14.25 bonus (2pm shift)
Requirements: Driver''s license, Insurance, Own vehicle, Heavy lifting
WorkWhile labels: Flat rate, Bonus

Sign up with WorkWhile and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.workwhile.ai/for-workers', 'Transportation and Warehousing', '48', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on WorkWhile']::text[], 95, 109, 'shift', 'jitsu|delivery driver flat rate|south san francisco ca'),
  ('workwhile', 'santa-clara-convention-center-general-labor-santa-clara-ca', 'General Labor', 'Santa Clara Convention Center', 'Santa Clara, CA', 'General Labor with Santa Clara Convention Center, booked through WorkWhile.

Shifts (as listed on 2026-09-27):
• Sat 9/26, 2:30pm – 11:00pm

Pay: $22/hr
Requirements: English proficiency, Heavy lifting

Sign up with WorkWhile and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.workwhile.ai/for-workers', 'Arts, Entertainment, and Recreation', '71', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on WorkWhile']::text[], 22, 22, 'hour', 'santa clara convention center|general labor|santa clara ca'),
  ('workwhile', 'shoreline-amphitheatre-prep-cook-mountain-view-ca', 'Prep Cook', 'Shoreline Amphitheatre', 'Mountain View, CA', 'Prep Cook with Shoreline Amphitheatre, booked through WorkWhile.

Shifts (as listed on 2026-09-27):
• Sat 9/26, 2:00pm – 11:30pm
• Sat 10/3, 1:30pm – 11:00pm

Pay: $23/hr, plus a $75 bonus on 9/26
Requirements: Food handler card
WorkWhile labels: Bonus

Sign up with WorkWhile and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.workwhile.ai/for-workers', 'Accommodation and Food Services', '72', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on WorkWhile']::text[], 23, 23, 'hour', 'shoreline amphitheatre|prep cook|mountain view ca'),
  ('workwhile', 'shoreline-amphitheatre-dishwasher-mountain-view-ca', 'Dishwasher', 'Shoreline Amphitheatre', 'Mountain View, CA', 'Dishwasher with Shoreline Amphitheatre, booked through WorkWhile.

Shifts (as listed on 2026-09-27):
• Sat 10/3, 5:00pm – 12:00am

Pay: $22/hr
Requirements: Experience needed

Sign up with WorkWhile and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.workwhile.ai/for-workers', 'Accommodation and Food Services', '72', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on WorkWhile']::text[], 22, 22, 'hour', 'shoreline amphitheatre|dishwasher|mountain view ca'),
  ('workwhile', 'thistle-prep-cook-kitchen-experience-vacaville-ca', 'Prep Cook – Kitchen Experience', 'Thistle', 'Vacaville, CA', 'Prep Cook – Kitchen Experience with Thistle, booked through WorkWhile.

Shifts (as listed on 2026-09-27):
• Sat 9/26 + Sat 10/3, 2:30pm – 11:00pm

Pay: $20/hr
Requirements: Experience needed, English proficiency, Heavy lifting

Sign up with WorkWhile and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.workwhile.ai/for-workers', 'Accommodation and Food Services', '72', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on WorkWhile']::text[], 20, 20, 'hour', 'thistle|prep cook kitchen experience|vacaville ca'),
  ('workwhile', 'thistle-dishwasher-vacaville-ca', 'Dishwasher', 'Thistle', 'Vacaville, CA', 'Dishwasher with Thistle, booked through WorkWhile.

Shifts (as listed on 2026-09-27):
• Sat 9/26, 2:30pm – 11:00pm
• Sat 9/26, 10:30pm – 6:00am

Pay: $20/hr (2:30pm shift); $21/hr (10:30pm shift)
Requirements: Heavy lifting

Sign up with WorkWhile and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.workwhile.ai/for-workers', 'Accommodation and Food Services', '72', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on WorkWhile']::text[], 20, 21, 'hour', 'thistle|dishwasher|vacaville ca'),
  ('instawork', 'azazie-event-setup-and-takedown-walnut-creek-ca', 'Event Setup and Takedown', 'Azazie', 'Walnut Creek, CA', 'Event Setup and Takedown with Azazie, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Sat 9/26, 3:00pm – 8:00pm

Pay: $19.61/hr
Requirements: None listed
Instawork labels: Paid backup

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Arts, Entertainment, and Recreation', '71', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 19.61, 19.61, 'hour', 'azazie|event setup and takedown|walnut creek ca'),
  ('instawork', 'azazie-general-labor-walnut-creek-ca', 'General Labor', 'Azazie', 'Walnut Creek, CA', 'General Labor with Azazie, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Sun 9/27, 3:00pm – 5:00pm

Pay: $20/hr
Requirements: None listed

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Retail Trade', '44', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 20, 20, 'hour', 'azazie|general labor|walnut creek ca'),
  ('instawork', 'bluestar-refreshment-services-general-labor-fremont-ca', 'General Labor', 'Bluestar Refreshment Services', 'Fremont, CA', 'General Labor with Bluestar Refreshment Services, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Fri 10/2, 2:00am – 10:30am

Pay: $18.78/hr
Requirements: None listed
Instawork labels: Multi-day

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Accommodation and Food Services', '72', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 18.78, 18.78, 'hour', 'bluestar refreshment services|general labor|fremont ca'),
  ('instawork', 'desicrew-solutions-general-labor-san-jose-ca', 'General Labor', 'DesiCrew Solutions', 'San Jose, CA', 'General Labor with DesiCrew Solutions, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Mon 9/28 + Fri 10/2, 9:00am – 10:30am
• Mon 9/28 + Fri 10/2, 1:00pm – 2:30pm
• Mon 9/28 + Fri 10/2, 2:30pm – 4:00pm

Pay: $26.37/hr
Requirements: None listed

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Administrative and Support Services', '56', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 26.37, 26.37, 'hour', 'desicrew solutions|general labor|san jose ca'),
  ('instawork', 'jitsu-warehouse-associate-entry-level-san-leandro-ca', 'Warehouse Associate – Entry Level', 'Jitsu', 'San Leandro, CA', 'Warehouse Associate – Entry Level with Jitsu, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Sat 9/26, 6:00pm – 12:30am
• Sat 9/26, 8:15pm – 4:30am
• Sun 9/27, 5:30pm – 2:30am

Pay: $18/hr
Requirements: None listed
Instawork labels: Long-term, W-2

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Transportation and Warehousing', '48', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 18, 18, 'hour', 'jitsu|warehouse associate entry level|san leandro ca'),
  ('instawork', 'legends-at-shoreline-amphitheatre-alcohol-compliance-monitor-mountain-view-ca', 'Alcohol Compliance Monitor', 'Legends at Shoreline Amphitheatre', 'Mountain View, CA', 'Alcohol Compliance Monitor with Legends at Shoreline Amphitheatre, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Sat 9/26, 4:00pm – 10:00pm

Pay: $19.70/hr plus tips
Requirements: None listed
Instawork labels: Needs approval, Tips

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Accommodation and Food Services', '72', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 19.7, 19.7, 'hour', 'legends at shoreline amphitheatre|alcohol compliance monitor|mountain view ca'),
  ('instawork', 'levi-s-stadium-concession-stand-worker-santa-clara-ca', 'Concession / Stand Worker', 'Levi''s Stadium', 'Santa Clara, CA', 'Concession / Stand Worker with Levi''s Stadium, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Sun 9/27, 8:00am – 6:00pm

Pay: $19/hr
Requirements: None listed

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Accommodation and Food Services', '72', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 19, 19, 'hour', 'levi s stadium|concession stand worker|santa clara ca'),
  ('instawork', 'off-the-grid-sf-event-setup-and-takedown-pleasant-hill-ca', 'Event Setup and Takedown', 'Off the Grid SF', 'Pleasant Hill, CA', 'Event Setup and Takedown with Off the Grid SF, booked through Instawork.

Shifts (as listed on 2026-09-27):
• 3:00pm – 5:00pm

Pay: $19.65/hr
Requirements: None listed

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Arts, Entertainment, and Recreation', '71', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 19.65, 19.65, 'hour', 'off the grid sf|event setup and takedown|pleasant hill ca'),
  ('instawork', 'aramark-oracle-park-concession-stand-worker-san-francisco-ca', 'Concession / Stand Worker', 'Aramark (Oracle Park)', 'San Francisco, CA', 'Concession / Stand Worker with Aramark (Oracle Park), booked through Instawork.

Shifts (as listed on 2026-09-27):
• Sun 9/27, 9:45am – 2:45pm

Pay: $21.48/hr
Requirements: None listed

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Accommodation and Food Services', '72', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 21.48, 21.48, 'hour', 'aramark oracle park|concession stand worker|san francisco ca'),
  ('instawork', 'palisades-hospitality-general-labor-olema-ca', 'General Labor', 'Palisades Hospitality', 'Olema, CA', 'General Labor with Palisades Hospitality, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Tue 9/29, 10:00am – 3:00pm

Pay: $23.63/hr (was $25.99)
Requirements: None listed
Instawork labels: Top Pro bonus

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Accommodation and Food Services', '72', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 23.63, 23.63, 'hour', 'palisades hospitality|general labor|olema ca'),
  ('instawork', 'picnic-driver-san-francisco-ca', 'Driver', 'Picnic', 'San Francisco, CA', 'Driver with Picnic, booked through Instawork.

Shifts (as listed on 2026-09-27):
• 10:00am – 12:00pm
• 10:00am – 12:30pm
• 10:30am – 12:00pm

Pay: $29.66–$35.77/hr
Requirements: None listed
Instawork labels: Long-term

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Transportation and Warehousing', '48', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 29.66, 35.77, 'hour', 'picnic|driver|san francisco ca'),
  ('instawork', 'priority-shift-applications-driver-san-jose-ca', 'Driver', 'Priority Shift Applications', 'San Jose, CA', 'Driver with Priority Shift Applications, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Mon 9/28 + Wed 9/30, 8:00am – 5:00pm

Pay: $25/hr
Requirements: None listed
Instawork labels: Multi-day, Trial shift

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Transportation and Warehousing', '48', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 25, 25, 'hour', 'priority shift applications|driver|san jose ca'),
  ('instawork', 'priority-shift-applications-home-recording-host-dallas-tx', 'Home Recording Host', 'Priority Shift Applications', 'Dallas, TX', 'Home Recording Host with Priority Shift Applications, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Sun 9/27, Mon 9/28, Wed 9/30, 10:00am – 1:00pm

Pay: $20/hr
Requirements: None listed

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Administrative and Support Services', '56', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 20, 20, 'hour', 'priority shift applications|home recording host|dallas tx'),
  ('instawork', 'tacit-general-labor-san-francisco-ca', 'General Labor', 'tacit', 'San Francisco, CA', 'General Labor with tacit, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Sun 9/27 – Wed 9/30, 15 four-hour shifts from 6:45am to 9:15pm (e.g. 6:45am – 10:45am, 12:00pm – 4:00pm, 5:15pm – 9:15pm)

Pay: $19.61/hr
Requirements: None listed

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Administrative and Support Services', '56', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 19.61, 19.61, 'hour', 'tacit|general labor|san francisco ca'),
  ('instawork', 'tacit-data-collector-san-jose-ca', 'Data Collector', 'tacit', 'San Jose, CA', 'Data Collector with tacit, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Mon 9/28 – Wed 9/30 + Fri 10/2, 7:00am – 10:30am
• 10:45am – 2:15pm
• 2:30pm – 6:00pm
• 6:15pm – 9:45pm

Pay: $20/hr
Requirements: None listed

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Professional, Scientific, and Technical Services', '54', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 20, 20, 'hour', 'tacit|data collector|san jose ca'),
  ('instawork', 'ux-study-santa-clara-paid-research-participant-santa-clara-ca', 'Paid Research Participant', 'UX Study Santa Clara', 'Santa Clara, CA', 'Paid Research Participant with UX Study Santa Clara, booked through Instawork.

Shifts (as listed on 2026-09-27):
• Mon 9/28, Wed 9/30, Fri 10/2, 8:30am – 11:30am
• 11:30am – 2:30pm
• 2:30pm – 5:30pm
• 5:30pm – 8:30pm

Pay: $33.33/hr
Requirements: None listed

Sign up with Instawork and book this shift in their app. Shift times change daily, so check the app for what''s open now.', 'https://www.instawork.com/worker', 'Professional, Scientific, and Technical Services', '54', 'temporary', 'Temporary', 'entry', false, '2026-09-27T12:00:00Z', '2026-10-12T06:59:59.000Z', 'hourly', ARRAY['Shift work on Instawork']::text[], 33.33, 33.33, 'hour', 'ux study santa clara|paid research participant|santa clara ca')
ON CONFLICT (source, external_id) DO UPDATE SET
  title = EXCLUDED.title,
  company_name = EXCLUDED.company_name,
  location = EXCLUDED.location,
  description = EXCLUDED.description,
  apply_url = EXCLUDED.apply_url,
  industry = EXCLUDED.industry,
  naics_code = EXCLUDED.naics_code,
  employment_type = EXCLUDED.employment_type,
  type = EXCLUDED.type,
  seniority = EXCLUDED.seniority,
  remote = EXCLUDED.remote,
  posted_at = EXCLUDED.posted_at,
  valid_through = EXCLUDED.valid_through,
  track = EXCLUDED.track,
  track_reasons = EXCLUDED.track_reasons,
  pay_min = EXCLUDED.pay_min,
  pay_max = EXCLUDED.pay_max,
  pay_unit = EXCLUDED.pay_unit,
  fingerprint = EXCLUDED.fingerprint,
  last_seen_at = now(),
  status = 'active';

-- Listings that dropped off the sheet come down.
UPDATE public.jobs
SET status = 'closed'
WHERE source IN ('bluecrew', 'workwhile', 'instawork')
  AND status <> 'closed'
  AND external_id NOT IN ('collision-auto-parts-driver-hayward-ca', 'jitsu-warehouse-associate-san-leandro-ca', 'sharebite-server-san-francisco-ca', 'advantage-solutions-costco-sample-demonstrator-newark-ca', 'jitsu-delivery-driver-san-leandro-ca', 'jitsu-delivery-driver-flat-rate-south-san-francisco-ca', 'santa-clara-convention-center-general-labor-santa-clara-ca', 'shoreline-amphitheatre-prep-cook-mountain-view-ca', 'shoreline-amphitheatre-dishwasher-mountain-view-ca', 'thistle-prep-cook-kitchen-experience-vacaville-ca', 'thistle-dishwasher-vacaville-ca', 'azazie-event-setup-and-takedown-walnut-creek-ca', 'azazie-general-labor-walnut-creek-ca', 'bluestar-refreshment-services-general-labor-fremont-ca', 'desicrew-solutions-general-labor-san-jose-ca', 'jitsu-warehouse-associate-entry-level-san-leandro-ca', 'legends-at-shoreline-amphitheatre-alcohol-compliance-monitor-mountain-view-ca', 'levi-s-stadium-concession-stand-worker-santa-clara-ca', 'off-the-grid-sf-event-setup-and-takedown-pleasant-hill-ca', 'aramark-oracle-park-concession-stand-worker-san-francisco-ca', 'palisades-hospitality-general-labor-olema-ca', 'picnic-driver-san-francisco-ca', 'priority-shift-applications-driver-san-jose-ca', 'priority-shift-applications-home-recording-host-dallas-tx', 'tacit-general-labor-san-francisco-ca', 'tacit-data-collector-san-jose-ca', 'ux-study-santa-clara-paid-research-participant-santa-clara-ca');

-- Equity filter: close listings whose employer is on a ratings list and misses
-- its cutoff ("all" mode: must pass every list it's on; "any": at least one).
WITH listing(external_id, normalized_name) AS (
  VALUES
    ('collision-auto-parts-driver-hayward-ca', 'collision auto parts'),
    ('jitsu-warehouse-associate-san-leandro-ca', 'jitsu'),
    ('sharebite-server-san-francisco-ca', 'sharebite'),
    ('advantage-solutions-costco-sample-demonstrator-newark-ca', 'advantage solutions'),
    ('jitsu-delivery-driver-san-leandro-ca', 'jitsu'),
    ('jitsu-delivery-driver-flat-rate-south-san-francisco-ca', 'jitsu'),
    ('santa-clara-convention-center-general-labor-santa-clara-ca', 'santa clara convention center'),
    ('shoreline-amphitheatre-prep-cook-mountain-view-ca', 'shoreline amphitheatre'),
    ('shoreline-amphitheatre-dishwasher-mountain-view-ca', 'shoreline amphitheatre'),
    ('thistle-prep-cook-kitchen-experience-vacaville-ca', 'thistle'),
    ('thistle-dishwasher-vacaville-ca', 'thistle'),
    ('azazie-event-setup-and-takedown-walnut-creek-ca', 'azazie'),
    ('azazie-general-labor-walnut-creek-ca', 'azazie'),
    ('bluestar-refreshment-services-general-labor-fremont-ca', 'bluestar refreshment services'),
    ('desicrew-solutions-general-labor-san-jose-ca', 'desicrew solutions'),
    ('jitsu-warehouse-associate-entry-level-san-leandro-ca', 'jitsu'),
    ('legends-at-shoreline-amphitheatre-alcohol-compliance-monitor-mountain-view-ca', 'legends at shoreline amphitheatre'),
    ('levi-s-stadium-concession-stand-worker-santa-clara-ca', 'levi s stadium'),
    ('off-the-grid-sf-event-setup-and-takedown-pleasant-hill-ca', 'off grid sf'),
    ('aramark-oracle-park-concession-stand-worker-san-francisco-ca', 'aramark oracle park'),
    ('palisades-hospitality-general-labor-olema-ca', 'palisades hospitality'),
    ('picnic-driver-san-francisco-ca', 'picnic'),
    ('priority-shift-applications-driver-san-jose-ca', 'priority shift applications'),
    ('priority-shift-applications-home-recording-host-dallas-tx', 'priority shift applications'),
    ('tacit-general-labor-san-francisco-ca', 'tacit'),
    ('tacit-data-collector-san-jose-ca', 'tacit'),
    ('ux-study-santa-clara-paid-research-participant-santa-clara-ca', 'ux study santa clara')
), verdicts AS (
  SELECT l.external_id,
         bool_and(CASE WHEN r.source = 'just_capital' THEN r.rank <= s.just_capital_max_rank
                       ELSE r.score >= s.as_you_sow_min_score END) AS passes_all,
         bool_or(CASE WHEN r.source = 'just_capital' THEN r.rank <= s.just_capital_max_rank
                      ELSE r.score >= s.as_you_sow_min_score END) AS passes_any,
         s.ratings_mode
  FROM listing l
  JOIN public.company_ratings r ON r.normalized_name = l.normalized_name
  JOIN public.scout_settings s ON s.id = 1 AND s.ratings_enabled
  GROUP BY l.external_id, s.ratings_mode
)
UPDATE public.jobs j
SET status = 'closed',
    track_reasons = ARRAY['Employer below the equity filter cutoff']
FROM verdicts v
WHERE j.source IN ('bluecrew', 'workwhile', 'instawork')
  AND j.external_id = v.external_id
  AND NOT (CASE WHEN v.ratings_mode = 'any' THEN v.passes_any ELSE v.passes_all END);
