-- =========================================================================
-- Seed /careers → Events from the Bay Area events sheet (61 events).
--
-- The sheet has no organiser or link column, so those stay NULL and the
-- cards show no "Details" button until a url is filled in.
-- industry is the sheet's leading sector; "General"/"Careers" rows are left
-- NULL so they land in the page's "General" group.
-- Times are Pacific. Safe to re-run: rows upsert on (source, external_id).
-- =========================================================================

INSERT INTO public.career_events
  (source, external_id, title, industry, event_type, venue, location, cost_note, description, starts_at, ends_at)
SELECT 'events_sheet', v.*
FROM (VALUES
  ('creative-fundraising-abundance-vs-scarcity-2026-10-23', 'CREATIVE FUNDRAISING: Abundance vs Scarcity', 'Nonprofit', 'workshop', 'Homebridge, 1035 Market St', 'San Francisco, CA', 'Free', 'Workshop on creative, abundance-minded approaches to nonprofit fundraising.', '2026-10-23 12:00 America/Los_Angeles'::timestamptz, NULL),
  ('bay-area-capital-connections-conference-2026-10-15', 'Bay Area Capital Connections Conference', 'Nonprofit', 'conference', 'BLOC15 Event Venue, 252 2nd St', 'Oakland, CA', '$33.85 - $65.87', 'Day of connection, learning and funding opportunities for Bay Area entrepreneurs and community leaders.', '2026-10-15 10:30 America/Los_Angeles'::timestamptz, '2026-10-15 16:00 America/Los_Angeles'::timestamptz),
  ('rotary-club-of-oakland-3-weekly-club-meeting-speaker-linda-s-2026-10-15', 'Rotary Club of Oakland #3 Weekly Club Meeting (Speaker: Linda Shively)', 'Nonprofit', 'networking', 'Henry J. Kaiser Center for the Arts', 'Oakland, CA', 'Free', 'Weekly service club lunch with speaker Linda Shively on navigating change.', '2026-10-15 12:00 America/Los_Angeles'::timestamptz, NULL),
  ('corporate-connections-live-san-francisco-lunch-with-corporat-2026-10-06', 'Corporate Connections LIVE San Francisco - Lunch with Corporate Funders', 'Nonprofit', 'networking', '1 California St', 'San Francisco, CA', '$58.74', 'Panel of corporate funders on how employee volunteerism shapes grants and sponsorships, plus networking lunch.', '2026-10-06 11:00 America/Los_Angeles'::timestamptz, '2026-10-06 13:30 America/Los_Angeles'::timestamptz),
  ('2026-building-san-francisco-s-future-workforce-through-high-2026-10-07', '2026 Building San Francisco''s Future Workforce Through High-Impact Tutoring', 'Nonprofit', 'other', 'Southeast Community Center, 1550 Evans Ave', 'San Francisco, CA', 'Free', 'Forum on tutoring, workforce development and cross-sector collaboration for students and communities.', '2026-10-07 09:00 America/Los_Angeles'::timestamptz, '2026-10-07 15:30 America/Los_Angeles'::timestamptz),
  ('non-profits-and-business-networking-elevating-your-potential-2026-10-07', 'Non-Profits and Business Networking (Elevating Your Potential - SF)', 'Nonprofit', 'networking', 'The Showdown, 1268 Grant Ave', 'San Francisco, CA', 'Free - $22.59', 'Evening mixer connecting nonprofit and business professionals, newcomers welcome.', '2026-10-07 18:00 America/Los_Angeles'::timestamptz, '2026-10-07 20:00 America/Los_Angeles'::timestamptz),
  ('2026-east-bay-high-impact-tutoring-innovation-forum-2026-10-08', '2026 East Bay High-Impact Tutoring Innovation Forum', 'Nonprofit', 'networking', 'Alameda County Office of Education, 313 W Winton Ave', 'Hayward, CA', 'Free', 'Forum on learning acceleration, student supports and expanded learning across Alameda County.', '2026-10-08 08:30 America/Los_Angeles'::timestamptz, '2026-10-08 14:00 America/Los_Angeles'::timestamptz),
  ('mentor-walks-san-francisco-get-guidance-and-grow-your-networ-2026-10-14', 'Mentor Walks San Francisco: Get Guidance and Grow Your Network', 'Nonprofit', 'networking', 'Ferry Building', 'San Francisco, CA', '$35.00', 'One-hour walk-and-talk mentoring and networking session for women at any career stage.', '2026-10-14 07:00 America/Los_Angeles'::timestamptz, '2026-10-14 08:30 America/Los_Angeles'::timestamptz),
  ('beyond-the-grant-what-do-i-post-creating-authentic-content-2026-10-15', 'Beyond the Grant: What Do I Post? Creating Authentic Content', 'Nonprofit', 'workshop', '826 N Hillview Dr', 'Milpitas, CA', '$20.00', 'Workshop on creating authentic social content that connects people with your mission.', '2026-10-15 18:00 America/Los_Angeles'::timestamptz, '2026-10-15 19:30 America/Los_Angeles'::timestamptz),
  ('reel-stories-college-and-career-readiness-roundtables-2026-10-26', 'Reel Stories College and Career Readiness Roundtables', 'Nonprofit', 'other', 'KQED, 2601 Mariposa St', 'San Francisco, CA', '$17.85', 'Small-group roundtables linking emerging filmmakers with industry pros, festival programmers and university reps.', '2026-10-26 17:00 America/Los_Angeles'::timestamptz, '2026-10-26 19:30 America/Los_Angeles'::timestamptz),
  ('grant-hacks-for-artists-workshop-2026-10-26', 'Grant Hacks for Artists Workshop', 'Nonprofit', 'workshop', 'The BEAM, 1189 65th St', 'Oakland, CA', '$23.18', 'Artist professional development workshop on finding and winning grants.', '2026-10-26 18:00 America/Los_Angeles'::timestamptz, '2026-10-26 20:00 America/Los_Angeles'::timestamptz),
  ('oakland-nonprofit-exchange-2026-10-28', 'Oakland Nonprofit Exchange', 'Nonprofit', 'networking', 'Stagebridge, 2501 Harrison St', 'Oakland, CA', 'Free', 'Monthly gathering for Oakland nonprofit leaders to exchange ideas and resources.', '2026-10-28 17:00 America/Los_Angeles'::timestamptz, '2026-10-28 18:30 America/Los_Angeles'::timestamptz),
  ('career-connect-community-job-career-fair-for-native-adults-2026-11-06', 'CAREER CONNECT: Community Job & Career Fair (for Native adults)', NULL, 'job_fair', '3050 International Blvd', 'Oakland, CA', 'Free', 'Job and career fair connecting Native adults with employers, career pathways and workforce resources.', '2026-11-06 10:00 America/Los_Angeles'::timestamptz, '2026-11-06 16:00 America/Los_Angeles'::timestamptz),
  ('venture-philanthropy-leader-jim-bildner-turning-hope-into-ac-2026-12-04', 'Venture Philanthropy Leader Jim Bildner: Turning Hope Into Action', 'Nonprofit', 'other', 'The Commonwealth Club, 110 The Embarcadero', 'San Francisco, CA', '$17.08', 'Talk by venture philanthropy leader Jim Bildner on tackling poverty, food insecurity and health care.', '2026-12-04 18:00 America/Los_Angeles'::timestamptz, '2026-12-04 19:00 America/Los_Angeles'::timestamptz),
  ('making-the-ask-fundraising-workshop-2027-01-20', 'Making the Ask Fundraising Workshop', 'Nonprofit', 'workshop', '330 Twin Dolphin Dr', 'Redwood City, CA', '$161.90', 'In-person workshop on confidently making a fundraising ask.', '2027-01-20 13:00 America/Los_Angeles'::timestamptz, '2027-01-20 16:00 America/Los_Angeles'::timestamptz),
  ('nonprofit-leadership-certificate-boot-camp-3-days-2027-04-27', 'Nonprofit Leadership Certificate Boot Camp (3 days)', 'Nonprofit', 'workshop', '330 Twin Dolphin Dr', 'Redwood City, CA', '$402.00 - $802.15', 'Three-day, not-for-credit certificate course for new and seasoned nonprofit professionals.', '2027-04-27 09:00 America/Los_Angeles'::timestamptz, '2027-04-29 16:00 America/Los_Angeles'::timestamptz),
  ('data-streaming-summit-2026-the-data-agent-conference-2-days-2026-10-07', 'Data Streaming Summit 2026: The Data + Agent Conference (2 days)', 'Technology', 'conference', 'Hotel Nikko San Francisco, 222 Mason St', 'San Francisco, CA', 'Free - $267.54', 'Conference on real-time data infrastructure powering AI agents and streaming systems.', '2026-10-07 09:00 America/Los_Angeles'::timestamptz, '2026-10-08 17:00 America/Los_Angeles'::timestamptz),
  ('productcon-san-francisco-the-ai-conference-for-product-leade-2026-10-07', '#ProductCon San Francisco: The AI Conference for Product Leaders', 'Technology', 'conference', 'SVN West, 10 Van Ness Ave', 'San Francisco, CA', 'Free - $2,000.00', 'Product management conference by and for product leaders, focused on AI.', '2026-10-07 09:00 America/Los_Angeles'::timestamptz, '2026-10-07 17:00 America/Los_Angeles'::timestamptz),
  ('tech-week-networking-event-in-san-francisco-2026-10-07', 'Tech Week: Networking Event in San Francisco', 'Technology', 'networking', 'Rick & Roxy''s, 2131 Lombard St', 'San Francisco, CA', 'Free - $28.52', 'Evening networking with investors, tech experts and entrepreneurs during SF Tech Week.', '2026-10-07 19:00 America/Los_Angeles'::timestamptz, '2026-10-07 22:00 America/Los_Angeles'::timestamptz),
  ('ai-is-hiring-who-gets-in-sf-tech-workforce-forum-2026-10-08', 'AI Is Hiring: Who Gets In? SF Tech Workforce Forum', 'Technology', 'other', 'The Box SF - Pressroom Gallery, 1069 Howard St', 'San Francisco, CA', 'Free - $82.00', 'Forum on AI hiring trends and who is getting hired in tech.', '2026-10-08 18:00 America/Los_Angeles'::timestamptz, '2026-10-08 20:30 America/Los_Angeles'::timestamptz),
  ('sf-tech-business-connection-night-2026-10-10', 'SF Tech & Business Connection Night', 'Technology', 'networking', 'SoMa Social, 121 7th St', 'San Francisco, CA', 'Free - $64.80', 'Casual networking night for tech and business professionals.', '2026-10-10 18:00 America/Los_Angeles'::timestamptz, '2026-10-10 20:00 America/Los_Angeles'::timestamptz),
  ('elc-annual-2026-2-days-2026-10-13', 'ELC Annual 2026 (2 days)', 'Technology', 'conference', 'Gateway Pavilion, Fort Mason Center, 2 Marina Blvd', 'San Francisco, CA', 'Free', 'Engineering leadership conference built around peer conversations.', '2026-10-13 08:00 America/Los_Angeles'::timestamptz, '2026-10-14 16:00 America/Los_Angeles'::timestamptz),
  ('tech-networking-event-in-san-francisco-2026-10-14', 'Tech Networking Event in San Francisco', 'Technology', 'networking', 'Iron Horse Cocktails, 25 Maiden Ln', 'San Francisco, CA', '$17.47', 'Ticketed evening mixer for San Francisco tech professionals.', '2026-10-14 18:30 America/Los_Angeles'::timestamptz, '2026-10-14 21:00 America/Los_Angeles'::timestamptz),
  ('lavender-town-queer-game-dev-meetup-2026-10-16', 'Lavender Town - Queer Game Dev Meetup', 'Technology', 'networking', 'The Museum of Art and Digital Entertainment, 921 Washington St', 'Oakland, CA', 'Free - $12.51', 'Monthly social for queer, women and BIPOC game developers and allies.', '2026-10-16 18:00 America/Los_Angeles'::timestamptz, '2026-10-16 21:00 America/Los_Angeles'::timestamptz),
  ('sf-women-in-tech-founders-professionals-networking-night-2026-10-19', 'SF Women in Tech: Founders & Professionals Networking Night', 'Technology', 'networking', 'Lush Lounge, 1221 Polk St', 'San Francisco, CA', '$9.85 - $39.19', 'Networking night for women founders and professionals in tech and startups.', '2026-10-19 19:00 America/Los_Angeles'::timestamptz, '2026-10-19 22:00 America/Los_Angeles'::timestamptz),
  ('zero-trust-for-ai-securing-models-data-and-autonomous-agents-2026-10-22', 'Zero Trust for AI: Securing Models, Data, and Autonomous Agents', 'Technology', 'networking', 'Cloudflare, 101 Townsend St', 'San Francisco, CA', 'Free', 'Talk on Zero Trust strategies for securing AI models, data and agents.', '2026-10-22 17:00 America/Los_Angeles'::timestamptz, '2026-10-22 19:00 America/Los_Angeles'::timestamptz),
  ('product-camp-silicon-valley-2026-2026-10-24', 'Product Camp Silicon Valley 2026', 'Technology', 'conference', 'Plug and Play Tech Center, 440 N Wolfe Rd', 'Sunnyvale, CA', '$69.07 - $177.91', 'Product manager community event on how AI is redefining product management.', '2026-10-24 09:00 America/Los_Angeles'::timestamptz, '2026-10-24 16:00 America/Los_Angeles'::timestamptz),
  ('odsc-ai-west-2026-conference-3-days-2026-10-27', 'ODSC AI West 2026 Conference (3 days)', 'Technology', 'conference', 'Hyatt Regency San Francisco Airport, 1333 Old Bayshore Hwy', 'Burlingame, CA', 'Free - $2,947.63', 'Large data science and AI conference with practitioners and business leaders.', '2026-10-27 09:00 America/Los_Angeles'::timestamptz, '2026-10-29 17:30 America/Los_Angeles'::timestamptz),
  ('san-francisco-physical-ai-workshop-and-meetup-2026-10-28', 'San Francisco Physical AI Workshop and Meetup', 'Technology', 'workshop', 'Antler San Francisco (3rd Floor), 144 Townsend St', 'San Francisco, CA', 'Free', 'Technical talks and meetup on physical AI and robotics.', '2026-10-28 17:30 America/Los_Angeles'::timestamptz, '2026-10-28 20:30 America/Los_Angeles'::timestamptz),
  ('bay-area-tech-connect-product-x-growth-x-operations-exchange-2026-10-29', 'Bay Area Tech Connect: Product x Growth x Operations Exchange', 'Technology', 'networking', '731-747 Commercial St', 'San Francisco, CA', 'Free - $1,000.00', 'Structured networking across product, growth, operations and startup talent.', '2026-10-29 18:30 America/Los_Angeles'::timestamptz, '2026-10-29 20:45 America/Los_Angeles'::timestamptz),
  ('the-anti-hype-conference-for-open-source-analytics-and-ai-2026-11-02', 'The Anti-Hype Conference for Open Source Analytics and AI', 'Technology', 'conference', 'AWS Builder Loft, 525 Market St', 'San Francisco, CA', 'Free', 'Vendor-free technical talks from engineers on open source analytics and AI.', '2026-11-02 09:30 America/Los_Angeles'::timestamptz, '2026-11-02 17:00 America/Los_Angeles'::timestamptz),
  ('techequity-ai-summit-2026-talks-ai-agent-workshops-4-days-2026-11-03', 'TechEquity AI Summit 2026: Talks + AI Agent Workshops (4 days)', 'Technology', 'conference', '135 Constitution Dr', 'Menlo Park, CA', 'Free - $1,975.93', 'Talks, networking and hands-on AI agent workshops on AI and tech fairness.', '2026-11-03 09:00 America/Los_Angeles'::timestamptz, '2026-11-06 16:00 America/Los_Angeles'::timestamptz),
  ('the-career-fork-in-the-road-reinventing-your-career-for-what-2026-10-08', 'The Career Fork in the Road: Reinventing Your Career for What''s Next', NULL, 'other', 'TechSoup, 435 Brannan St', 'San Francisco, CA', 'Free', 'Talk and career-mapping exercise on reinventing your career when your current role stops creating growth.', '2026-10-08 18:00 America/Los_Angeles'::timestamptz, '2026-10-08 20:30 America/Los_Angeles'::timestamptz),
  ('sf-fashion-week-ft-conference-ai-implementation-in-fashion-b-2026-10-08', 'SF Fashion Week FT Conference: AI Implementation in Fashion & Beauty', 'Fashion & Beauty', 'conference', 'Cinta Aveda Institute, 305 Kearny St', 'San Francisco, CA', '$12.16', 'SF Fashion Week session on practical uses of AI across the fashion and beauty industry.', '2026-10-08 18:00 America/Los_Angeles'::timestamptz, '2026-10-08 21:00 America/Los_Angeles'::timestamptz),
  ('envisioning-a-more-diverse-future-for-publishing-2026-10-08', 'Envisioning a More Diverse Future for Publishing', 'Media', 'networking', 'Chronicle Books, 680 2nd St', 'San Francisco, CA', 'Free', 'Evening of networking for Bay Area publishing professionals.', '2026-10-08 17:30 America/Los_Angeles'::timestamptz, '2026-10-08 19:30 America/Los_Angeles'::timestamptz),
  ('sf-legal-professionals-speed-networking-2026-10-12', 'SF Legal Professionals: Speed Networking', 'Legal', 'networking', 'ERIA Marina, 2300 Chestnut St', 'San Francisco, CA', 'See listing', 'Speed networking for legal professionals, benefiting the SFLPA Scholarship Program.', '2026-10-12 18:00 America/Los_Angeles'::timestamptz, '2026-10-12 21:00 America/Los_Angeles'::timestamptz),
  ('finance-networking-event-in-san-francisco-2026-10-14', 'Finance Networking Event in San Francisco', 'Finance', 'networking', 'Iron Horse Cocktails, 25 Maiden Ln', 'San Francisco, CA', '$17.47', 'Evening mixer for finance industry professionals looking to expand their connections.', '2026-10-14 18:30 America/Los_Angeles'::timestamptz, '2026-10-14 21:00 America/Los_Angeles'::timestamptz),
  ('alameda-job-fair-2026-2026-10-15', 'Alameda Job Fair 2026', NULL, 'job_fair', 'South Shore Center, 523 South Shore Center W', 'Alameda, CA', 'Free', 'Job fair with local city government, school district, parks, transportation, shipping, retail and restaurant employers.', '2026-10-15 14:00 America/Los_Angeles'::timestamptz, '2026-10-15 16:00 America/Los_Angeles'::timestamptz),
  ('q3-artwork-network-2026-10-15', 'Q3 Artwork+Network', 'Arts', 'networking', 'Thornton Tomasetti, 235 Montgomery St', 'San Francisco, CA', 'Free', 'Quarterly social with industry professionals featuring the work of a Bay Area artist.', '2026-10-15 16:30 America/Los_Angeles'::timestamptz, '2026-10-15 19:30 America/Los_Angeles'::timestamptz),
  ('california-sports-entertainment-career-expo-at-chase-center-2026-10-16', 'California Sports & Entertainment Career Expo at Chase Center', NULL, 'job_fair', 'Chase Center, 1 Warriors Way', 'San Francisco, CA', '$79.88', 'Hosted by the Golden State Warriors; meet hiring managers from California sports and entertainment organizations.', '2026-10-16 12:00 America/Los_Angeles'::timestamptz, '2026-10-16 14:30 America/Los_Angeles'::timestamptz),
  ('childcare-fall-forum-a-pathway-to-quality-accessible-child-c-2026-10-19', 'Childcare Fall Forum: A Pathway to Quality, Accessible Child Care for All', 'Education', 'other', 'Glide, 330 Ellis St', 'San Francisco, CA', 'Free', 'Discussion of practical ways to make child care affordable and accessible.', '2026-10-19 17:00 America/Los_Angeles'::timestamptz, '2026-10-19 18:30 America/Los_Angeles'::timestamptz),
  ('ibclc-mentoring-circle-2026-10-21', 'IBCLC Mentoring Circle', 'Healthcare', 'networking', 'Sports Basement Presidio, 610 Old Mason St', 'San Francisco, CA', '$28.52', 'Guidance and community for new and emerging lactation consultants building a practice.', '2026-10-21 10:00 America/Los_Angeles'::timestamptz, '2026-10-21 12:00 America/Los_Angeles'::timestamptz),
  ('food-allergy-fund-innovation-forum-san-francisco-2026-10-21', 'Food Allergy Fund Innovation Forum - San Francisco', 'Healthcare', 'other', 'The Commonwealth Club, 110 The Embarcadero', 'San Francisco, CA', '$100.00 - $1,068.91', 'Forum to learn about, connect around and invest in food allergy innovation.', '2026-10-21 16:00 America/Los_Angeles'::timestamptz, '2026-10-21 18:30 America/Los_Angeles'::timestamptz),
  ('women-s-emerging-leadership-forum-welf-2026-2026-10-23', 'Women''s Emerging Leadership Forum (WELF) 2026', 'Business', 'other', 'Visa Global Headquarters, 300 Toni Stone Crossing', 'San Francisco, CA', '$40.00 - $150.00', 'Annual forum designed to help women reach their full potential in the workplace.', '2026-10-23 08:15 America/Los_Angeles'::timestamptz, '2026-10-23 14:15 America/Los_Angeles'::timestamptz),
  ('ncc-acrp-career-bootcamp-2026-clinical-research-careers-in-t-2026-10-24', 'NCC ACRP Career Bootcamp 2026: Clinical Research Careers in the AI Era', 'Healthcare', 'workshop', 'Genentech, 1 DNA Way', 'South San Francisco, CA', 'Free', 'How AI is reshaping clinical research careers, with industry leaders and career growth opportunities.', '2026-10-24 08:30 America/Los_Angeles'::timestamptz, '2026-10-24 13:00 America/Los_Angeles'::timestamptz),
  ('stempeers-bay-area-fall-meetup-2026-2026-10-24', 'STEMPeers Bay Area Fall Meetup 2026', 'Science', 'other', 'Mission Bay Housing Community Room, 525 Nelson Rising Ln', 'San Francisco, CA', '$7.18', 'Panel on careers in academia, faculty applications and non-PI university roles.', '2026-10-24 11:00 America/Los_Angeles'::timestamptz, '2026-10-24 13:00 America/Los_Angeles'::timestamptz),
  ('sf-summit-leading-the-future-of-real-estate-2026-10-26', 'SF Summit: Leading the Future of Real Estate', 'Real Estate', 'conference', 'Hyatt Regency San Francisco Downtown SOMA, 50 3rd St', 'San Francisco, CA', '$25.00 - $43.45', 'Day of education and collaboration with real estate industry leaders and innovators.', '2026-10-26 09:00 America/Los_Angeles'::timestamptz, '2026-10-26 17:00 America/Los_Angeles'::timestamptz),
  ('gamesforum-san-francisco-2026-2-days-2026-10-26', 'Gamesforum San Francisco 2026 (2 days)', 'Media', 'conference', 'Hotel Nikko San Francisco, 222 Mason St', 'San Francisco, CA', '£133.10 - £189.89', 'Mobile game growth event covering acquisition, monetization and retention.', '2026-10-26 08:00 America/Los_Angeles'::timestamptz, '2026-10-27 17:00 America/Los_Angeles'::timestamptz),
  ('appsforum-san-francisco-2-days-2026-10-26', 'Appsforum San Francisco (2 days)', 'Media', 'conference', 'Hotel Nikko San Francisco, 222 Mason St', 'San Francisco, CA', '£133.10 - £189.89', 'App growth conference covering acquisition, monetization and retention strategies.', '2026-10-26 08:00 America/Los_Angeles'::timestamptz, '2026-10-27 17:00 America/Los_Angeles'::timestamptz),
  ('sf-biotech-pharma-medtech-networking-pitch-mixer-2026-10-26', 'SF BioTech, Pharma, MedTech Networking & Pitch Mixer', 'Biotech', 'networking', 'The Treasury, 200 Bush St', 'San Francisco, CA', '$9.85 - $39.19', 'Live pitches and networking with biotech and pharma founders, investors and experts.', '2026-10-26 19:00 America/Los_Angeles'::timestamptz, '2026-10-26 22:00 America/Los_Angeles'::timestamptz),
  ('iiex-west-2026-market-research-insights-analytics-conference-2026-10-27', 'IIEX West 2026: Market Research, Insights & Analytics Conference (2 days)', 'Market Research & Analytics', 'conference', 'Pier 27, 27 The Embarcadero', 'San Francisco, CA', 'Free - $1,383.71', 'Case studies and networking for market research, insights, analytics and UX professionals.', '2026-10-27 07:00 America/Los_Angeles'::timestamptz, '2026-10-28 17:00 America/Los_Angeles'::timestamptz),
  ('one-way-summit-2026-the-flagship-event-for-immigrant-entrepr-2026-10-28', 'One Way Summit 2026: The Flagship Event for Immigrant Entrepreneurship', 'Business', 'conference', 'The Commonwealth Club, 110 The Embarcadero', 'San Francisco, CA', '$129.00 - $499.00', 'Annual gathering for immigrant founders, builders and investors.', '2026-10-28 09:30 America/Los_Angeles'::timestamptz, '2026-10-28 17:00 America/Los_Angeles'::timestamptz),
  ('san-francisco-engineering-energy-transportation-networking-e-2026-10-28', 'San Francisco Engineering, Energy & Transportation Networking Event', 'Engineering', 'networking', 'Novela, 662 Mission St', 'San Francisco, CA', '$9.85 - $21.05', 'Evening mixer for professionals in engineering, energy and transportation.', '2026-10-28 19:00 America/Los_Angeles'::timestamptz, '2026-10-28 21:00 America/Los_Angeles'::timestamptz),
  ('hdaa-california-chapter-fall-conference-2026-10-30', 'HDAA California Chapter Fall Conference', 'Healthcare', 'conference', 'Stanford Hospital Assembly Hall, 500 Pasteur Dr', 'Palo Alto, CA', 'Free', 'Half-day chapter conference with talks and in-person networking.', '2026-10-30 09:00 America/Los_Angeles'::timestamptz, '2026-10-30 13:00 America/Los_Angeles'::timestamptz),
  ('the-14th-structural-proteomics-symposium-3-days-2026-11-04', 'The 14th Structural Proteomics Symposium (3 days)', 'Science', 'conference', 'UCSF Mission Bay, 1700 4th St', 'San Francisco, CA', '$157.34 - $520.29', 'QBI UCSF hosts the West Coast debut of this structural proteomics research symposium.', '2026-11-04 10:00 America/Los_Angeles'::timestamptz, '2026-11-06 18:00 America/Los_Angeles'::timestamptz),
  ('leading-for-equity-in-complex-systems-2-days-2026-11-05', 'Leading for Equity in Complex Systems (2 days)', 'Business', 'workshop', 'Oakstop, 2323 Broadway', 'Oakland, CA', '$1,200.00', 'Two-day in-person institute applying a complexity lens to equity leadership and change work.', '2026-11-05 08:00 America/Los_Angeles'::timestamptz, '2026-11-06 16:00 America/Los_Angeles'::timestamptz),
  ('notes-from-the-field-towards-liberation-and-freedom-2026-11-07', 'Notes from the Field: Towards Liberation and Freedom', 'Healthcare', 'conference', 'California Institute of Integral Studies, 1453 Mission St', 'San Francisco, CA', 'Free - $42.99', 'CIIS Clinical Psychology Department''s annual one-day conference reimagining clinical work.', '2026-11-07 09:00 America/Los_Angeles'::timestamptz, '2026-11-07 15:30 America/Los_Angeles'::timestamptz),
  ('2026-rising-together-the-bay-adapt-summit-2026-11-09', '2026 Rising Together: The Bay Adapt Summit', 'Environment', 'conference', 'Exploratorium', 'San Francisco, CA', 'Free', 'Convening for Bay Area climate adaptation leaders and practitioners.', '2026-11-09 10:00 America/Los_Angeles'::timestamptz, '2026-11-09 21:00 America/Los_Angeles'::timestamptz),
  ('start-s-early-development-leaders-biotech-roundtable-san-fra-2026-11-10', 'START''s Early Development Leaders Biotech Roundtable - San Francisco', 'Biotech', 'other', 'Hotel Kabuki, 1625 Post St', 'San Francisco, CA', 'Free', 'Breakfast roundtable on early-phase oncology research.', '2026-11-10 07:30 America/Los_Angeles'::timestamptz, '2026-11-10 09:00 America/Los_Angeles'::timestamptz),
  ('san-francisco-law-real-estate-construction-networking-event-2026-11-12', 'San Francisco Law, Real Estate & Construction Networking Event', 'Legal', 'networking', 'Soundtrack, 3192 16th St', 'San Francisco, CA', '$9.85 - $21.05', 'Evening mixer for professionals in law, real estate and construction.', '2026-11-12 19:00 America/Los_Angeles'::timestamptz, '2026-11-12 21:00 America/Los_Angeles'::timestamptz),
  ('2026-neurotrauma-symposium-2026-12-07', '2026 Neurotrauma Symposium', 'Healthcare', 'conference', 'Mission Bay Conference Center, 1675 Owens St', 'San Francisco, CA', '$108.55 - $250.00', 'Research talks and discussion on brain injuries and treatments.', '2026-12-07 08:00 America/Los_Angeles'::timestamptz, '2026-12-07 17:00 America/Los_Angeles'::timestamptz)
) AS v(external_id, title, industry, event_type, venue, location, cost_note, description, starts_at, ends_at)
ON CONFLICT (source, external_id) DO UPDATE SET
  title = EXCLUDED.title,
  industry = EXCLUDED.industry,
  event_type = EXCLUDED.event_type,
  venue = EXCLUDED.venue,
  location = EXCLUDED.location,
  cost_note = EXCLUDED.cost_note,
  description = EXCLUDED.description,
  starts_at = EXCLUDED.starts_at,
  ends_at = EXCLUDED.ends_at,
  updated_at = now();
